export const ADMINSETTING_FETCH_ENTITY_DATA_SUCCESS = "ADMINSETTING_FETCH_ENTITY_DATA_SUCCESS";
export const ADMINSETTING_SELECT_NEW_ENTITY = "ADMINSETTING_SELECT_NEW_ENTITY";

export const ADMINSETTING_FETCH_MASTER_DATA_SUCCESS = "ADMINSETTING_FETCH_MASTER_DATA_SUCCESS";
export const ADMINSETTING_FETCH_LIST_FIELDS_SUCCESS = "ADMINSETTING_FETCH_LIST_FIELDS_SUCCESS";
export const ADMINSETTING_FETCH_LIST_DATA_SUCCESS = "ADMINSETTING_FETCH_LIST_DATA_SUCCESS";
export const ADMINSETTING_FETCH_DATASET_SUCCESS = "ADMINSETTING_FETCH_DATASET_SUCCESS";

export const ADMINSETTING_SET_PAGINATION = "ADMINSETTING_SET_PAGINATION";
export const ADMINSETTING_SET_PAGE_SIZE = "ADMINSETTING_SET_PAGE_SIZE";
export const ADMINSETTING_INCREMENT_COUNT = "ADMINSETTING_INCREMENT_COUNT";
export const ADMINSETTING_SET_DATASETID = "ADMINSETTING_SET_DATASETID";

export const ADMINSETTING_SET_ADV_MATCHED_LOOKUP = "ADMINSETTING_SET_ADV_MATCHED_LOOKUP";
export const ADMINSETTING_SET_MATCHED_LOOKUP = "ADMINSETTING_SET_MATCHED_LOOKUP";
export const ADMINSETTING_TOGGLE_COLUMN_ISMAPPING = "ADMINSETTING_TOGGLE_COLUMN_ISMAPPING";
export const ADMINSETTING_TOGGLE_FILTER_ISMAPPING = "ADMINSETTING_TOGGLE_FILTER_ISMAPPING";
export const ADMINSETTING_CREATE_HOR_GROUPBYDATA = "ADMINSETTING_CREATE_HOR_GROUPBYDATA";
export const ADMINSETTING_CHANGE_HORIZONTAL_GROUPBY = "ADMINSETTING_CHANGE_HORIZONTAL_GROUPBY";

export const ADMINSETTING_SELECTED_FILTER_VALUE = "ADMINSETTING_SELECTED_FILTER_VALUE";
export const ADMINSETTING_ADD_ADDITIONAL_FILTER = "ADMINSETTING_ADD_ADDITIONAL_FILTER";
export const ADMINSETTING_SET_DROPDOWN_CHECKED = "ADMINSETTING_SET_DROPDOWN_CHECKED";
export const ADMINSETTING_SET_MULTISELECT_CHECKED = "ADMINSETTING_SET_MULTISELECT_CHECKED";
export const ADMINSETTING_SET_ADV_MULTISELECT_CHECKED =
  "ADMINSETTING_SET_ADV_MULTISELECT_CHECKED";
export const ADMINSETTING_SET_ADV_DROPDOWN_CHECKED = "ADMINSETTING_SET_ADV_DROPDOWN_CHECKED";

export const ADMINSETTING_REMOVE_ALL_FILTER = "ADMINSETTING_REMOVE_ALL_FILTER";
export const ADMINSETTING_REMOVE_QUICK_FILTER = "ADMINSETTING_REMOVE_QUICK_FILTER";
export const ADMINSETTING_REMOVE_ADVANCED_FILTER = "ADMINSETTING_REMOVE_ADVANCED_FILTER";

export const ADMINSETTING_QUICK_TEXT_VALUE = "ADMINSETTING_QUICK_TEXT_VALUE";
export const ADMINSETTING_RESET_QUICK_FILTER_VALUES = "ADMINSETTING_RESET_QUICK_FILTER_VALUES";

export const ADMINSETTING_CREATE_NEW_DATASET = "ADMINSETTING_CREATE_NEW_DATASET";
export const ADMINSETTING_EDIT_DATASET = "ADMINSETTING_EDIT_DATASET";
export const ADMINSETTING_GET_NEW_DATASET_INFO_SUCCESS =
  "ADMINSETTING_GET_NEW_DATASET_INFO_SUCCESS";
export const ADMINSETTING_DELETE_DATASET_DB = "ADMINSETTING_DELETE_DATASET_DB";

export const ADMINSETTING_SORTED_COLUMN = "ADMINSETTING_SORTED_COLUMN";
export const ADMINSETTING_SET_COLUMN_SEQ = "ADMINSETTING_SET_COLUMN_SEQ";
export const ADMINSETTING_SET_NEW_LAYOUT = "ADMINSETTING_SET_NEW_LAYOUT";
export const ADMINSETTING_SET_DATEPICKER_VALUE = "ADMINSETTING_SET_DATEPICKER_VALUE";
export const ADMINSETTING_SET_WEEKFILTER_VALUE = "ADMINSETTING_SET_WEEKFILTER_VALUE";
export const ADMINSETTING_RESET_DATE_FILTERS = "ADMINSETTING_RESET_DATE_FILTERS";
export const ADMINSETTING_CHANGE_MASTER_DATA = "ADMINSETTING_CHANGE_MASTER_DATA";
export const ADMINSETTING_GET_USERNAME = "ADMINSETTING_GET_USERNAME";
export const ADMINSETTING_SET_LOADING = "ADMINSETTING_SET_LOADING";
