export const ACTIVITYLOG_FETCH_ENTITY_DATA_SUCCESS = "ACTIVITYLOG_FETCH_ENTITY_DATA_SUCCESS";
export const ACTIVITYLOG_SELECT_NEW_ENTITY = "ACTIVITYLOG_SELECT_NEW_ENTITY";

export const ACTIVITYLOG_FETCH_MASTER_DATA_SUCCESS = "ACTIVITYLOG_FETCH_MASTER_DATA_SUCCESS";
export const ACTIVITYLOG_FETCH_LIST_FIELDS_SUCCESS = "ACTIVITYLOG_FETCH_LIST_FIELDS_SUCCESS";
export const ACTIVITYLOG_FETCH_LIST_DATA_SUCCESS = "ACTIVITYLOG_FETCH_LIST_DATA_SUCCESS";
export const ACTIVITYLOG_FETCH_DATASET_SUCCESS = "ACTIVITYLOG_FETCH_DATASET_SUCCESS";

export const ACTIVITYLOG_SET_PAGINATION = "ACTIVITYLOG_SET_PAGINATION";
export const ACTIVITYLOG_SET_PAGE_SIZE = "ACTIVITYLOG_SET_PAGE_SIZE";
export const ACTIVITYLOG_INCREMENT_COUNT = "ACTIVITYLOG_INCREMENT_COUNT";
export const ACTIVITYLOG_SET_DATASETID = "ACTIVITYLOG_SET_DATASETID";

export const ACTIVITYLOG_SET_ADV_MATCHED_LOOKUP = "ACTIVITYLOG_SET_ADV_MATCHED_LOOKUP";
export const ACTIVITYLOG_SET_MATCHED_LOOKUP = "ACTIVITYLOG_SET_MATCHED_LOOKUP";
export const ACTIVITYLOG_TOGGLE_COLUMN_ISMAPPING = "ACTIVITYLOG_TOGGLE_COLUMN_ISMAPPING";
export const ACTIVITYLOG_TOGGLE_FILTER_ISMAPPING = "ACTIVITYLOG_TOGGLE_FILTER_ISMAPPING";
export const ACTIVITYLOG_CREATE_HOR_GROUPBYDATA = "ACTIVITYLOG_CREATE_HOR_GROUPBYDATA";
export const ACTIVITYLOG_CREATE_HOR_GROUPBYDATA_DIRECTION =
  "ACTIVITYLOG_CREATE_HOR_GROUPBYDATA_DIRECTION";
export const ACTIVITYLOG_CHANGE_HORIZONTAL_GROUPBY = "ACTIVITYLOG_CHANGE_HORIZONTAL_GROUPBY";

export const ACTIVITYLOG_SELECTED_FILTER_VALUE = "ACTIVITYLOG_SELECTED_FILTER_VALUE";
export const ACTIVITYLOG_ADD_ADDITIONAL_FILTER = "ACTIVITYLOG_ADD_ADDITIONAL_FILTER";
export const ACTIVITYLOG_SET_DROPDOWN_CHECKED = "ACTIVITYLOG_SET_DROPDOWN_CHECKED";
export const ACTIVITYLOG_SET_MULTISELECT_CHECKED = "ACTIVITYLOG_SET_MULTISELECT_CHECKED";
export const ACTIVITYLOG_SET_ADV_MULTISELECT_CHECKED =
  "ACTIVITYLOG_SET_ADV_MULTISELECT_CHECKED";
export const ACTIVITYLOG_SET_ADV_DROPDOWN_CHECKED = "ACTIVITYLOG_SET_ADV_DROPDOWN_CHECKED";

export const ACTIVITYLOG_REMOVE_ALL_FILTER = "ACTIVITYLOG_REMOVE_ALL_FILTER";
export const ACTIVITYLOG_REMOVE_QUICK_FILTER = "ACTIVITYLOG_REMOVE_QUICK_FILTER";
export const ACTIVITYLOG_REMOVE_ADVANCED_FILTER = "ACTIVITYLOG_REMOVE_ADVANCED_FILTER";

export const ACTIVITYLOG_QUICK_TEXT_VALUE = "ACTIVITYLOG_QUICK_TEXT_VALUE";
export const ACTIVITYLOG_RESET_QUICK_FILTER_VALUES = "ACTIVITYLOG_RESET_QUICK_FILTER_VALUES";

export const ACTIVITYLOG_CREATE_NEW_DATASET = "ACTIVITYLOG_CREATE_NEW_DATASET";
export const ACTIVITYLOG_EDIT_DATASET = "ACTIVITYLOG_EDIT_DATASET";
export const ACTIVITYLOG_GET_NEW_DATASET_INFO_SUCCESS =
  "ACTIVITYLOG_GET_NEW_DATASET_INFO_SUCCESS";
export const ACTIVITYLOG_DELETE_DATASET_DB = "ACTIVITYLOG_DELETE_DATASET_DB";

export const ACTIVITYLOG_SORTED_COLUMN = "ACTIVITYLOG_SORTED_COLUMN";
export const ACTIVITYLOG_SET_COLUMN_SEQ = "ACTIVITYLOG_SET_COLUMN_SEQ";
export const ACTIVITYLOG_SET_NEW_LAYOUT = "ACTIVITYLOG_SET_NEW_LAYOUT";
export const ACTIVITYLOG_SET_DATEPICKER_VALUE = "ACTIVITYLOG_SET_DATEPICKER_VALUE";
export const ACTIVITYLOG_SET_WEEKFILTER_VALUE = "ACTIVITYLOG_SET_WEEKFILTER_VALUE";
export const ACTIVITYLOG_RESET_DATE_FILTERS = "ACTIVITYLOG_RESET_DATE_FILTERS";
export const ACTIVITYLOG_CHANGE_MASTER_DATA = "ACTIVITYLOG_CHANGE_MASTER_DATA";
export const ACTIVITYLOG_GET_USERNAME = "ACTIVITYLOG_GET_USERNAME";
export const ACTIVITYLOG_GET_USERMAIL = "ACTIVITYLOG_GET_USERMAIL";
export const ACTIVITYLOG_SET_LOADING = "ACTIVITYLOG_SET_LOADING";
export const ACTIVITYLOG_EDIT_CELL = "ACTIVITYLOG_EDIT_CELL";
export const ACTIVITYLOG_SET_CURRENTPAGE = "ACTIVITYLOG_SET_CURRENTPAGE";
export const ACTIVITYLOG_RESET_EDIT_CELL = "ACTIVITYLOG_RESET_EDIT_CELL";
export const ACTIVITYLOG_SETVERTICAL_GROUPBY_DIR = "ACTIVITYLOG_SETVERTICAL_GROUPBY_DIR";
export const ACTIVITYLOG_CREATE_VER_GROUPBYDATA = "ACTIVITYLOG_CREATE_VER_GROUPBYDATA";
export const ACTIVITYLOG_SETMATRIXROWCOLUMN = "ACTIVITYLOG_SETMATRIXROWCOLUMN";
