export const FOLLOWUP_FETCH_ENTITY_DATA_SUCCESS =
  "FOLLOWUP_FETCH_ENTITY_DATA_SUCCESS";
export const FOLLOWUP_SELECT_NEW_ENTITY = "FOLLOWUP_SELECT_NEW_ENTITY";

export const FOLLOWUP_FETCH_MASTER_DATA_SUCCESS =
  "FOLLOWUP_FETCH_MASTER_DATA_SUCCESS";
export const FOLLOWUP_FETCH_LIST_FIELDS_SUCCESS =
  "FOLLOWUP_FETCH_LIST_FIELDS_SUCCESS";
export const FOLLOWUP_FETCH_LIST_DATA_SUCCESS =
  "FOLLOWUP_FETCH_LIST_DATA_SUCCESS";
export const FOLLOWUP_FETCH_DATASET_SUCCESS = "FOLLOWUP_FETCH_DATASET_SUCCESS";

export const FOLLOWUP_SET_PAGINATION = "FOLLOWUP_SET_PAGINATION";
export const FOLLOWUP_SET_PAGE_SIZE = "FOLLOWUP_SET_PAGE_SIZE";
export const FOLLOWUP_INCREMENT_COUNT = "FOLLOWUP_INCREMENT_COUNT";
export const FOLLOWUP_SET_DATASETID = "FOLLOWUP_SET_DATASETID";
export const FOLLOWUP_SET_ADV_MATCHED_LOOKUP =
  "FOLLOWUP_SET_ADV_MATCHED_LOOKUP";
export const FOLLOWUP_SET_MATCHED_LOOKUP = "FOLLOWUP_SET_MATCHED_LOOKUP";
export const FOLLOWUP_TOGGLE_COLUMN_ISMAPPING =
  "FOLLOWUP_TOGGLE_COLUMN_ISMAPPING";
export const FOLLOWUP_TOGGLE_FILTER_ISMAPPING =
  "FOLLOWUP_TOGGLE_FILTER_ISMAPPING";
export const FOLLOWUP_CREATE_HOR_GROUPBYDATA =
  "FOLLOWUP_CREATE_HOR_GROUPBYDATA";
export const FOLLOWUP_CHANGE_HORIZONTAL_GROUPBY =
  "FOLLOWUP_CHANGE_HORIZONTAL_GROUPBY";

export const FOLLOWUP_SELECTED_FILTER_VALUE = "FOLLOWUP_SELECTED_FILTER_VALUE";
export const FOLLOWUP_ADD_ADDITIONAL_FILTER = "FOLLOWUP_ADD_ADDITIONAL_FILTER";
export const FOLLOWUP_SET_DROPDOWN_CHECKED = "FOLLOWUP_SET_DROPDOWN_CHECKED";
export const FOLLOWUP_SET_MULTISELECT_CHECKED =
  "FOLLOWUP_SET_MULTISELECT_CHECKED";
export const FOLLOWUP_SET_ADV_MULTISELECT_CHECKED =
  "FOLLOWUP_SET_ADV_MULTISELECT_CHECKED";
export const FOLLOWUP_SET_ADV_DROPDOWN_CHECKED =
  "FOLLOWUP_SET_ADV_DROPDOWN_CHECKED";

export const FOLLOWUP_REMOVE_ALL_FILTER = "FOLLOWUP_REMOVE_ALL_FILTER";
export const FOLLOWUP_REMOVE_QUICK_FILTER = "FOLLOWUP_REMOVE_QUICK_FILTER";
export const FOLLOWUP_REMOVE_ADVANCED_FILTER =
  "FOLLOWUP_REMOVE_ADVANCED_FILTER";

export const FOLLOWUP_QUICK_TEXT_VALUE = "FOLLOWUP_QUICK_TEXT_VALUE";
export const FOLLOWUP_RESET_QUICK_FILTER_VALUES =
  "FOLLOWUP_RESET_QUICK_FILTER_VALUES";

export const FOLLOWUP_CREATE_NEW_DATASET = "FOLLOWUP_CREATE_NEW_DATASET";
export const FOLLOWUP_EDIT_DATASET = "FOLLOWUP_EDIT_DATASET";
export const FOLLOWUP_GET_NEW_DATASET_INFO_SUCCESS =
  "FOLLOWUP_GET_NEW_DATASET_INFO_SUCCESS";
export const FOLLOWUP_DELETE_DATASET_DB = "FOLLOWUP_DELETE_DATASET_DB";

export const FOLLOWUP_SORTED_COLUMN = "FOLLOWUP_SORTED_COLUMN";
export const FOLLOWUP_SET_COLUMN_SEQ = "FOLLOWUP_SET_COLUMN_SEQ";
export const FOLLOWUP_SET_NEW_LAYOUT = "FOLLOWUP_SET_NEW_LAYOUT";
export const FOLLOWUP_SET_DATEPICKER_VALUE = "FOLLOWUP_SET_DATEPICKER_VALUE";
export const FOLLOWUP_SET_WEEKFILTER_VALUE = "FOLLOWUP_SET_WEEKFILTER_VALUE";

export const FOLLOWUP_RESET_DATE_FILTERS = "FOLLOWUP_RESET_DATE_FILTERS ";
export const FOLLOWUP_CHANGE_MASTER_DATA = "FOLLOWUP_CHANGE_MASTER_DATA ";

export const FOLLOWUP_GET_USERNAME = "FOLLOWUP_GET_USERNAME ";
export const FOLLOWUP_SET_LOADING = "FOLLOWUP_SET_LOADING ";
export const FOLLOWUP_SET_TRANSACTIONID = "FOLLOWUP_SET_TRANSACTIONID ";
export const FOLLOWUP_360_FETCH_LIST_FIELDS_SUCCESS =
  "FOLLOWUP_360_FETCH_LIST_FIELDS_SUCCESS ";
export const FOLLOWUP_360_TASK_ROW_DATA = "FOLLOWUP_360_TASK_ROW_DATA ";
export const FOLLOWUP_360_DATASET_SUCCESS = "FOLLOWUP_360_DATASET_SUCCESS ";
export const FOLLOWUP_SET_CURRENTPAGE = "FOLLOWUP_SET_CURRENTPAGE";
