export const JOURNEY_FETCH_ENTITY_DATA_SUCCESS =
  "JOURNEY_FETCH_ENTITY_DATA_SUCCESS";
export const JOURNEY_SELECT_NEW_ENTITY = "JOURNEY_SELECT_NEW_ENTITY";

export const JOURNEY_FETCH_MASTER_DATA_SUCCESS =
  "JOURNEY_FETCH_MASTER_DATA_SUCCESS";
export const JOURNEY_FETCH_LIST_FIELDS_SUCCESS =
  "JOURNEY_FETCH_LIST_FIELDS_SUCCESS";
export const JOURNEY_FETCH_LIST_DATA_SUCCESS =
  "JOURNEY_FETCH_LIST_DATA_SUCCESS";
export const JOURNEY_FETCH_DATASET_SUCCESS = "JOURNEY_FETCH_DATASET_SUCCESS";

export const JOURNEY_SET_PAGINATION = "JOURNEY_SET_PAGINATION";
export const JOURNEY_SET_PAGE_SIZE = "JOURNEY_SET_PAGE_SIZE";
export const JOURNEY_INCREMENT_COUNT = "JOURNEY_INCREMENT_COUNT";
export const JOURNEY_SET_DATASETID = "JOURNEY_SET_DATASETID";

export const JOURNEY_SET_ADV_MATCHED_LOOKUP = "JOURNEY_SET_ADV_MATCHED_LOOKUP";
export const JOURNEY_SET_MATCHED_LOOKUP = "JOURNEY_SET_MATCHED_LOOKUP";
export const JOURNEY_TOGGLE_COLUMN_ISMAPPING =
  "JOURNEY_TOGGLE_COLUMN_ISMAPPING";
export const JOURNEY_TOGGLE_FILTER_ISMAPPING =
  "JOURNEY_TOGGLE_FILTER_ISMAPPING";
export const JOURNEY_CREATE_HOR_GROUPBYDATA = "JOURNEY_CREATE_HOR_GROUPBYDATA";
export const JOURNEY_CHANGE_HORIZONTAL_GROUPBY =
  "JOURNEY_CHANGE_HORIZONTAL_GROUPBY";

export const JOURNEY_SELECTED_FILTER_VALUE = "JOURNEY_SELECTED_FILTER_VALUE";
export const JOURNEY_ADD_ADDITIONAL_FILTER = "JOURNEY_ADD_ADDITIONAL_FILTER";
export const JOURNEY_SET_DROPDOWN_CHECKED = "JOURNEY_SET_DROPDOWN_CHECKED";
export const JOURNEY_SET_MULTISELECT_CHECKED =
  "JOURNEY_SET_MULTISELECT_CHECKED";
export const JOURNEY_SET_ADV_MULTISELECT_CHECKED =
  "JOURNEY_SET_ADV_MULTISELECT_CHECKED";
export const JOURNEY_SET_ADV_DROPDOWN_CHECKED =
  "JOURNEY_SET_ADV_DROPDOWN_CHECKED";

export const JOURNEY_REMOVE_ALL_FILTER = "JOURNEY_REMOVE_ALL_FILTER";
export const JOURNEY_REMOVE_QUICK_FILTER = "JOURNEY_REMOVE_QUICK_FILTER";
export const JOURNEY_REMOVE_ADVANCED_FILTER = "JOURNEY_REMOVE_ADVANCED_FILTER";

export const JOURNEY_QUICK_TEXT_VALUE = "JOURNEY_QUICK_TEXT_VALUE";
export const JOURNEY_RESET_QUICK_FILTER_VALUES =
  "JOURNEY_RESET_QUICK_FILTER_VALUES";

export const JOURNEY_CREATE_NEW_DATASET = "JOURNEY_CREATE_NEW_DATASET";
export const JOURNEY_EDIT_DATASET = "JOURNEY_EDIT_DATASET";
export const JOURNEY_GET_NEW_DATASET_INFO_SUCCESS =
  "JOURNEY_GET_NEW_DATASET_INFO_SUCCESS";
export const JOURNEY_DELETE_DATASET_DB = "JOURNEY_DELETE_DATASET_DB";

export const JOURNEY_SORTED_COLUMN = "JOURNEY_SORTED_COLUMN";
export const JOURNEY_SET_COLUMN_SEQ = "JOURNEY_SET_COLUMN_SEQ";
export const JOURNEY_SET_NEW_LAYOUT = "JOURNEY_SET_NEW_LAYOUT";
export const JOURNEY_SET_DATEPICKER_VALUE = "JOURNEY_SET_DATEPICKER_VALUE";
export const JOURNEY_SET_WEEKFILTER_VALUE = "JOURNEY_SET_WEEKFILTER_VALUE";
export const JOURNEY_RESET_DATE_FILTERS = "JOURNEY_RESET_DATE_FILTERS";
export const JOURNEY_CHANGE_MASTER_DATA = "JOURNEY_CHANGE_MASTER_DATA";
export const JOURNEY_GET_USERNAME = "JOURNEY_GET_USERNAME";
export const JOURNEY_GET_USERMAIL = "JOURNEY_GET_USERMAIL";
export const JOURNEY_SET_LOADING = "JOURNEY_SET_LOADING";
export const JOURNEY_EDIT_CELL = "JOURNEY_EDIT_CELL";
export const JOURNEY_RESET_EDIT_CELL = "JOURNEY_RESET_EDIT_CELL";
