export const PROJECTVSSTATUSREPORT_FETCH_ENTITY_DATA_SUCCESS =
  "PROJECTVSSTATUSREPORT_FETCH_ENTITY_DATA_SUCCESS";
export const PROJECTVSSTATUSREPORT_SELECT_NEW_ENTITY =
  "PROJECTVSSTATUSREPORT_SELECT_NEW_ENTITY";

export const PROJECTVSSTATUSREPORT_FETCH_MASTER_DATA_SUCCESS =
  "PROJECTVSSTATUSREPORT_FETCH_MASTER_DATA_SUCCESS";
export const PROJECTVSSTATUSREPORT_FETCH_LIST_FIELDS_SUCCESS =
  "PROJECTVSSTATUSREPORT_FETCH_LIST_FIELDS_SUCCESS";
export const PROJECTVSSTATUSREPORT_FETCH_LIST_DATA_SUCCESS =
  "PROJECTVSSTATUSREPORT_FETCH_LIST_DATA_SUCCESS";
export const PROJECTVSSTATUSREPORT_FETCH_DATASET_SUCCESS =
  "PROJECTVSSTATUSREPORT_FETCH_DATASET_SUCCESS";

export const PROJECTVSSTATUSREPORT_SET_PAGINATION =
  "PROJECTVSSTATUSREPORT_SET_PAGINATION";
export const PROJECTVSSTATUSREPORT_SET_PAGE_SIZE =
  "PROJECTVSSTATUSREPORT_SET_PAGE_SIZE";
export const PROJECTVSSTATUSREPORT_INCREMENT_COUNT =
  "PROJECTVSSTATUSREPORT_INCREMENT_COUNT";
export const PROJECTVSSTATUSREPORT_SET_DATASETID =
  "PROJECTVSSTATUSREPORT_SET_DATASETID";
export const PROJECTVSSTATUSREPORT_SET_ADV_MATCHED_LOOKUP =
  "PROJECTVSSTATUSREPORT_SET_ADV_MATCHED_LOOKUP";
export const PROJECTVSSTATUSREPORT_SET_MATCHED_LOOKUP =
  "PROJECTVSSTATUSREPORT_SET_MATCHED_LOOKUP";
export const PROJECTVSSTATUSREPORT_TOGGLE_COLUMN_ISMAPPING =
  "PROJECTVSSTATUSREPORT_TOGGLE_COLUMN_ISMAPPING";
export const PROJECTVSSTATUSREPORT_TOGGLE_FILTER_ISMAPPING =
  "PROJECTVSSTATUSREPORT_TOGGLE_FILTER_ISMAPPING";
export const PROJECTVSSTATUSREPORT_CREATE_HOR_GROUPBYDATA =
  "PROJECTVSSTATUSREPORT_CREATE_HOR_GROUPBYDATA";
export const PROJECTVSSTATUSREPORT_CHANGE_HORIZONTAL_GROUPBY =
  "PROJECTVSSTATUSREPORT_CHANGE_HORIZONTAL_GROUPBY";

export const PROJECTVSSTATUSREPORT_SELECTED_FILTER_VALUE =
  "PROJECTVSSTATUSREPORT_SELECTED_FILTER_VALUE";
export const PROJECTVSSTATUSREPORT_ADD_ADDITIONAL_FILTER =
  "PROJECTVSSTATUSREPORT_ADD_ADDITIONAL_FILTER";
export const PROJECTVSSTATUSREPORT_SET_DROPDOWN_CHECKED =
  "PROJECTVSSTATUSREPORT_SET_DROPDOWN_CHECKED";
export const PROJECTVSSTATUSREPORT_SET_MULTISELECT_CHECKED =
  "PROJECTVSSTATUSREPORT_SET_MULTISELECT_CHECKED";
export const PROJECTVSSTATUSREPORT_SET_ADV_MULTISELECT_CHECKED =
  "PROJECTVSSTATUSREPORT_SET_ADV_MULTISELECT_CHECKED";
export const PROJECTVSSTATUSREPORT_SET_ADV_DROPDOWN_CHECKED =
  "PROJECTVSSTATUSREPORT_SET_ADV_DROPDOWN_CHECKED";

export const PROJECTVSSTATUSREPORT_REMOVE_ALL_FILTER =
  "PROJECTVSSTATUSREPORT_REMOVE_ALL_FILTER";
export const PROJECTVSSTATUSREPORT_REMOVE_QUICK_FILTER =
  "PROJECTVSSTATUSREPORT_REMOVE_QUICK_FILTER";
export const PROJECTVSSTATUSREPORT_REMOVE_ADVANCED_FILTER =
  "PROJECTVSSTATUSREPORT_REMOVE_ADVANCED_FILTER";

export const PROJECTVSSTATUSREPORT_QUICK_TEXT_VALUE =
  "PROJECTVSSTATUSREPORT_QUICK_TEXT_VALUE";
export const PROJECTVSSTATUSREPORT_RESET_QUICK_FILTER_VALUES =
  "PROJECTVSSTATUSREPORT_RESET_QUICK_FILTER_VALUES";

export const PROJECTVSSTATUSREPORT_CREATE_NEW_DATASET =
  "PROJECTVSSTATUSREPORT_CREATE_NEW_DATASET";
export const PROJECTVSSTATUSREPORT_EDIT_DATASET =
  "PROJECTVSSTATUSREPORT_EDIT_DATASET";
export const PROJECTVSSTATUSREPORT_GET_NEW_DATASET_INFO_SUCCESS =
  "PROJECTVSSTATUSREPORT_GET_NEW_DATASET_INFO_SUCCESS";
export const PROJECTVSSTATUSREPORT_DELETE_DATASET_DB =
  "PROJECTVSSTATUSREPORT_DELETE_DATASET_DB";

export const PROJECTVSSTATUSREPORT_SORTED_COLUMN =
  "PROJECTVSSTATUSREPORT_SORTED_COLUMN";
export const PROJECTVSSTATUSREPORT_SET_COLUMN_SEQ =
  "PROJECTVSSTATUSREPORT_SET_COLUMN_SEQ";
export const PROJECTVSSTATUSREPORT_SET_NEW_LAYOUT =
  "PROJECTVSSTATUSREPORT_SET_NEW_LAYOUT";
export const PROJECTVSSTATUSREPORT_SET_DATEPICKER_VALUE =
  "PROJECTVSSTATUSREPORT_SET_DATEPICKER_VALUE";
export const PROJECTVSSTATUSREPORT_SET_WEEKFILTER_VALUE =
  "PROJECTVSSTATUSREPORT_SET_WEEKFILTER_VALUE";
export const PROJECTVSSTATUSREPORT_RESET_DATE_FILTERS =
  "PROJECTVSSTATUSREPORT_RESET_DATE_FILTERS";
export const PROJECTVSSTATUSREPORT_CHANGE_MASTER_DATA =
  "PROJECTVSSTATUSREPORT_CHANGE_MASTER_DATA";
export const PROJECTVSSTATUSREPORT_GET_USERNAME =
  "PROJECTVSSTATUSREPORT_GET_USERNAME";
export const PROJECTVSSTATUSREPORT_SET_LOADING =
  "PROJECTVSSTATUSREPORT_SET_LOADING";
export const PROJECTVSSTATUSREPORT_SET_MONTHFILTER_VALUE =
  "PROJECTVSSTATUSREPORT_SET_MONTHFILTER_VALUE";
export const PROJECTVSSTATUSREPORT_SET_PLANMONTHFILTER_VALUE =
  "PROJECTVSSTATUSREPORT_SET_PLANMONTHFILTER_VALUE";
export const PROJECTVSSTATUSREPORT_SET_PLANWEEKFILTER_VALUE =
  "PROJECTVSSTATUSREPORT_SET_PLANWEEKFILTER_VALUE";

export const PROJECTVSSTATUSREPORT_SET_CURRENTPAGE =
  "PROJECTVSSTATUSREPORT_SET_CURRENTPAGE";
