export const NOTES_FETCH_ENTITY_DATA_SUCCESS =
  "NOTES_FETCH_ENTITY_DATA_SUCCESS";
export const NOTES_SELECT_NEW_ENTITY = "NOTES_SELECT_NEW_ENTITY";

export const NOTES_FETCH_MASTER_DATA_SUCCESS =
  "NOTES_FETCH_MASTER_DATA_SUCCESS";
export const NOTES_FETCH_LIST_FIELDS_SUCCESS =
  "NOTES_FETCH_LIST_FIELDS_SUCCESS";
export const NOTES_FETCH_LIST_DATA_SUCCESS = "NOTES_FETCH_LIST_DATA_SUCCESS";
export const NOTES_FETCH_DATASET_SUCCESS = "NOTES_FETCH_DATASET_SUCCESS";

export const NOTES_SET_PAGINATION = "NOTES_SET_PAGINATION";
export const NOTES_SET_PAGE_SIZE = "NOTES_SET_PAGE_SIZE";
export const NOTES_INCREMENT_COUNT = "NOTES_INCREMENT_COUNT";
export const NOTES_SET_DATASETID = "NOTES_SET_DATASETID";

export const NOTES_SET_ADV_MATCHED_LOOKUP = "NOTES_SET_ADV_MATCHED_LOOKUP";
export const NOTES_SET_MATCHED_LOOKUP = "NOTES_SET_MATCHED_LOOKUP";
export const NOTES_TOGGLE_COLUMN_ISMAPPING = "NOTES_TOGGLE_COLUMN_ISMAPPING";
export const NOTES_TOGGLE_FILTER_ISMAPPING = "NOTES_TOGGLE_FILTER_ISMAPPING";
export const NOTES_CREATE_HOR_GROUPBYDATA = "NOTES_CREATE_HOR_GROUPBYDATA";
export const NOTES_CHANGE_HORIZONTAL_GROUPBY =
  "NOTES_CHANGE_HORIZONTAL_GROUPBY";

export const NOTES_SELECTED_FILTER_VALUE = "NOTES_SELECTED_FILTER_VALUE";
export const NOTES_ADD_ADDITIONAL_FILTER = "NOTES_ADD_ADDITIONAL_FILTER";
export const NOTES_SET_DROPDOWN_CHECKED = "NOTES_SET_DROPDOWN_CHECKED";
export const NOTES_SET_MULTISELECT_CHECKED = "NOTES_SET_MULTISELECT_CHECKED";
export const NOTES_SET_ADV_MULTISELECT_CHECKED =
  "NOTES_SET_ADV_MULTISELECT_CHECKED";
export const NOTES_SET_ADV_DROPDOWN_CHECKED = "NOTES_SET_ADV_DROPDOWN_CHECKED";

export const NOTES_REMOVE_ALL_FILTER = "NOTES_REMOVE_ALL_FILTER";
export const NOTES_REMOVE_QUICK_FILTER = "NOTES_REMOVE_QUICK_FILTER";
export const NOTES_REMOVE_ADVANCED_FILTER = "NOTES_REMOVE_ADVANCED_FILTER";

export const NOTES_QUICK_TEXT_VALUE = "NOTES_QUICK_TEXT_VALUE";
export const NOTES_RESET_QUICK_FILTER_VALUES =
  "NOTES_RESET_QUICK_FILTER_VALUES";

export const NOTES_CREATE_NEW_DATASET = "NOTES_CREATE_NEW_DATASET";
export const NOTES_EDIT_DATASET = "NOTES_EDIT_DATASET";
export const NOTES_GET_NEW_DATASET_INFO_SUCCESS =
  "NOTES_GET_NEW_DATASET_INFO_SUCCESS";
export const NOTES_DELETE_DATASET_DB = "NOTES_DELETE_DATASET_DB";

export const NOTES_SORTED_COLUMN = "NOTES_SORTED_COLUMN";
export const NOTES_SET_COLUMN_SEQ = "NOTES_SET_COLUMN_SEQ";
export const NOTES_SET_NEW_LAYOUT = "NOTES_SET_NEW_LAYOUT";
export const NOTES_SET_DATEPICKER_VALUE = "NOTES_SET_DATEPICKER_VALUE";
export const NOTES_SET_WEEKFILTER_VALUE = "NOTES_SET_WEEKFILTER_VALUE";
export const NOTES_RESET_DATE_FILTERS = "NOTES_RESET_DATE_FILTERS";
export const NOTES_CHANGE_MASTER_DATA = "NOTES_CHANGE_MASTER_DATA";
export const NOTES_GET_USERNAME = "NOTES_GET_USERNAME";
export const NOTES_GET_USERMAIL = "NOTES_GET_USERMAIL";
export const NOTES_SET_LOADING = "NOTES_SET_LOADING";
export const NOTES_EDIT_CELL = "NOTES_EDIT_CELL";
export const NOTES_RESET_EDIT_CELL = "NOTES_RESET_EDIT_CELL";
export const NOTES_SET_CURRENTPAGE = "NOTES_SET_CURRENTPAGE";
