export const JOURNEY_HOME_ENTITY_ID = "JOURNEY_HOME_ENTITY_ID";
export const JOURNEY_HOME_FETCH_MASTER_DATA_SUCCESS = "JOURNEY_HOME_FETCH_MASTER_DATA_SUCCESS";

export const UPDATE_SECTION_STATUS_SUCCESS = "UPDATE_SECTION_STATUS_SUCCESS";
export const UPDATE_FIELD_STATUS_SUCCESS = "UPDATE_FIELD_STATUS_SUCCESS";