export const EXECUTION_FETCH_EXECUTION_DATA_SUCCESS =
  "EXECUTION_FETCH_EXECUTION_DATA_SUCCESS";
export const EXECUTION_SELECT_NEW_ENTITY = "EXECUTION_SELECT_NEW_ENTITY";

export const EXECUTION_FETCH_MASTER_DATA_SUCCESS =
  "EXECUTION_FETCH_MASTER_DATA_SUCCESS";
export const EXECUTION_FETCH_SUB_MASTER_DATA_SUCCESS =
  "EXECUTION_FETCH_SUB_MASTER_DATA_SUCCESS";
export const EXECUTION_FETCH_LIST_FIELDS_SUCCESS =
  "EXECUTION_FETCH_LIST_FIELDS_SUCCESS";
export const EXECUTION_FETCH_LIST_DATA_SUCCESS =
  "EXECUTION_FETCH_LIST_DATA_SUCCESS";
export const EXECUTION_FETCH_DATASET_SUCCESS =
  "EXECUTION_FETCH_DATASET_SUCCESS";

export const EXECUTION_SET_PAGINATION = "EXECUTION_SET_PAGINATION";
export const EXECUTION_SET_PAGE_SIZE = "EXECUTION_SET_PAGE_SIZE";
export const EXECUTION_INCREMENT_COUNT = "EXECUTION_INCREMENT_COUNT";
export const EXECUTION_SET_DATASETID = "EXECUTION_SET_DATASETID";

export const EXECUTION_SET_ADV_MATCHED_LOOKUP =
  "EXECUTION_SET_ADV_MATCHED_LOOKUP";
export const EXECUTION_SET_MATCHED_LOOKUP = "EXECUTION_SET_MATCHED_LOOKUP";
export const EXECUTION_TOGGLE_COLUMN_ISMAPPING =
  "EXECUTION_TOGGLE_COLUMN_ISMAPPING";
export const EXECUTION_TOGGLE_FILTER_ISMAPPING =
  "EXECUTION_TOGGLE_FILTER_ISMAPPING";
export const EXECUTION_CREATE_HOR_GROUPBYDATA =
  "EXECUTION_CREATE_HOR_GROUPBYDATA";
export const EXECUTION_CHANGE_HORIZONTAL_GROUPBY =
  "EXECUTION_CHANGE_HORIZONTAL_GROUPBY";

export const EXECUTION_SELECTED_FILTER_VALUE =
  "EXECUTION_SELECTED_FILTER_VALUE";
export const EXECUTION_ADD_ADDITIONAL_FILTER =
  "EXECUTION_ADD_ADDITIONAL_FILTER";
export const EXECUTION_SET_DROPDOWN_CHECKED = "EXECUTION_SET_DROPDOWN_CHECKED";
export const EXECUTION_SET_MULTISELECT_CHECKED =
  "EXECUTION_SET_MULTISELECT_CHECKED";
export const EXECUTION_SET_ADV_MULTISELECT_CHECKED =
  "EXECUTION_SET_ADV_MULTISELECT_CHECKED";
export const EXECUTION_SET_ADV_DROPDOWN_CHECKED =
  "EXECUTION_SET_ADV_DROPDOWN_CHECKED";

export const EXECUTION_REMOVE_ALL_FILTER = "EXECUTION_REMOVE_ALL_FILTER";
export const EXECUTION_REMOVE_QUICK_FILTER = "EXECUTION_REMOVE_QUICK_FILTER";
export const EXECUTION_REMOVE_ADVANCED_FILTER =
  "EXECUTION_REMOVE_ADVANCED_FILTER";

export const EXECUTION_QUICK_TEXT_VALUE = "EXECUTION_QUICK_TEXT_VALUE";
export const EXECUTION_RESET_QUICK_FILTER_VALUES =
  "EXECUTION_RESET_QUICK_FILTER_VALUES";

export const EXECUTION_CREATE_NEW_DATASET = "EXECUTION_CREATE_NEW_DATASET";
export const EXECUTION_EDIT_DATASET = "EXECUTION_EDIT_DATASET";
export const EXECUTION_GET_NEW_DATASET_INFO_SUCCESS =
  "EXECUTION_GET_NEW_DATASET_INFO_SUCCESS";
export const EXECUTION_DELETE_DATASET_DB = "EXECUTION_DELETE_DATASET_DB";

export const EXECUTION_SORTED_COLUMN = "EXECUTION_SORTED_COLUMN";
export const EXECUTION_SET_COLUMN_SEQ = "EXECUTION_SET_COLUMN_SEQ";
export const EXECUTION_SET_NEW_LAYOUT = "EXECUTION_SET_NEW_LAYOUT";

export const EXECUTION_SET_DATEPICKER_VALUE = "EXECUTION_SET_DATEPICKER_VALUE";
export const EXECUTION_SET_WEEKFILTER_VALUE = "EXECUTION_SET_WEEKFILTER_VALUE";

export const EXECUTION_RESET_DATE_FILTERS = "EXECUTION_RESET_DATE_FILTERS ";
export const EXECUTION_CHANGE_MASTER_DATA = "EXECUTION_CHANGE_MASTER_DATA ";

export const EXECUTION_GET_USERNAME = "EXECUTION_GET_USERNAME ";
export const EXECUTION_SET_LOADING = "EXECUTION_SET_LOADING ";
export const EXECUTION_SET_TRANSACTIONID = "EXECUTION_SET_TRANSACTIONID ";
export const EXECUTION_360_FETCH_LIST_FIELDS_SUCCESS =
  "EXECUTION_360_FETCH_LIST_FIELDS_SUCCESS ";
export const EXECUTION_360_TASK_ROW_DATA = "EXECUTION_360_TASK_ROW_DATA ";
export const EXECUTION_360_DATASET_SUCCESS = "EXECUTION_360_DATASET_SUCCESS ";
export const EXECUTION_360_FETCH_SUB_LIST_FIELDS_SUCCESS =
  "EXECUTION_360_FETCH_SUB_LIST_FIELDS_SUCCESS ";
export const EXECUTION_360_SUB_TASK_ROW_DATA =
  "EXECUTION_360_SUB_TASK_ROW_DATA ";
export const EXECUTION_360_SUB_DATASET_SUCCESS =
  "EXECUTION_360_SUB_DATASET_SUCCESS ";

export const EXECUTION_EDIT_CELL = "EXECUTION_EDIT_CELL ";
export const EXECUTION_RESET_EDIT_CELL = "EXECUTION_RESET_EDIT_CELL ";
export const EXECUTION_SET_CURRENTPAGE = "EXECUTION_SET_CURRENTPAGE";
