export const REPORT_FETCH_ENTITY_DATA_SUCCESS =
  "REPORT_FETCH_ENTITY_DATA_SUCCESS";
export const REPORT_SELECT_NEW_ENTITY = "REPORT_SELECT_NEW_ENTITY";

export const REPORT_FETCH_MASTER_DATA_SUCCESS =
  "REPORT_FETCH_MASTER_DATA_SUCCESS";
export const REPORT_FETCH_LIST_FIELDS_SUCCESS =
  "REPORT_FETCH_LIST_FIELDS_SUCCESS";
export const REPORT_FETCH_LIST_DATA_SUCCESS = "REPORT_FETCH_LIST_DATA_SUCCESS";
export const REPORT_FETCH_DATASET_SUCCESS = "REPORT_FETCH_DATASET_SUCCESS";

export const REPORT_SET_PAGINATION = "REPORT_SET_PAGINATION";
export const REPORT_SET_PAGE_SIZE = "REPORT_SET_PAGE_SIZE";
export const REPORT_INCREMENT_COUNT = "REPORT_INCREMENT_COUNT";
export const REPORT_SET_DATASETID = "REPORT_SET_DATASETID";
export const REPORT_SET_ADV_MATCHED_LOOKUP = "REPORT_SET_ADV_MATCHED_LOOKUP";
export const REPORT_SET_MATCHED_LOOKUP = "REPORT_SET_MATCHED_LOOKUP";
export const REPORT_TOGGLE_COLUMN_ISMAPPING = "REPORT_TOGGLE_COLUMN_ISMAPPING";
export const REPORT_TOGGLE_FILTER_ISMAPPING = "REPORT_TOGGLE_FILTER_ISMAPPING";
export const REPORT_CREATE_HOR_GROUPBYDATA = "REPORT_CREATE_HOR_GROUPBYDATA";
export const REPORT_CHANGE_HORIZONTAL_GROUPBY =
  "REPORT_CHANGE_HORIZONTAL_GROUPBY";

export const REPORT_SELECTED_FILTER_VALUE = "REPORT_SELECTED_FILTER_VALUE";
export const REPORT_ADD_ADDITIONAL_FILTER = "REPORT_ADD_ADDITIONAL_FILTER";
export const REPORT_SET_DROPDOWN_CHECKED = "REPORT_SET_DROPDOWN_CHECKED";
export const REPORT_SET_MULTISELECT_CHECKED = "REPORT_SET_MULTISELECT_CHECKED";
export const REPORT_SET_ADV_MULTISELECT_CHECKED =
  "REPORT_SET_ADV_MULTISELECT_CHECKED";
export const REPORT_SET_ADV_DROPDOWN_CHECKED =
  "REPORT_SET_ADV_DROPDOWN_CHECKED";

export const REPORT_REMOVE_ALL_FILTER = "REPORT_REMOVE_ALL_FILTER";
export const REPORT_REMOVE_QUICK_FILTER = "REPORT_REMOVE_QUICK_FILTER";
export const REPORT_REMOVE_ADVANCED_FILTER = "REPORT_REMOVE_ADVANCED_FILTER";

export const REPORT_QUICK_TEXT_VALUE = "REPORT_QUICK_TEXT_VALUE";
export const REPORT_RESET_QUICK_FILTER_VALUES =
  "REPORT_RESET_QUICK_FILTER_VALUES";

export const REPORT_CREATE_NEW_DATASET = "REPORT_CREATE_NEW_DATASET";
export const REPORT_EDIT_DATASET = "REPORT_EDIT_DATASET";
export const REPORT_GET_NEW_DATASET_INFO_SUCCESS =
  "REPORT_GET_NEW_DATASET_INFO_SUCCESS";
export const REPORT_DELETE_DATASET_DB = "REPORT_DELETE_DATASET_DB";

export const REPORT_SORTED_COLUMN = "REPORT_SORTED_COLUMN";
export const REPORT_SET_COLUMN_SEQ = "REPORT_SET_COLUMN_SEQ";
export const REPORT_SET_NEW_LAYOUT = "REPORT_SET_NEW_LAYOUT";
export const REPORT_SET_DATEPICKER_VALUE = "REPORT_SET_DATEPICKER_VALUE";
export const REPORT_SET_WEEKFILTER_VALUE = "REPORT_SET_WEEKFILTER_VALUE";
export const REPORT_RESET_DATE_FILTERS = "REPORT_RESET_DATE_FILTERS";
export const REPORT_CHANGE_MASTER_DATA = "REPORT_CHANGE_MASTER_DATA";
export const REPORT_GET_USERNAME = "REPORT_GET_USERNAME";
export const REPORT_SET_LOADING = "REPORT_SET_LOADING";

export const REPORT_SET_CURRENTPAGE = "REPORT_SET_CURRENTPAGE";
