export const FETCH_ENTITY_DATA_SUCCESS = "FETCH_ENTITY_DATA_SUCCESS";
export const SELECT_NEW_ENTITY = "SELECT_NEW_ENTITY";

export const FETCH_MASTER_DATA_SUCCESS = "FETCH_MASTER_DATA_SUCCESS";
export const FETCH_LIST_FIELDS_SUCCESS = "FETCH_LIST_FIELDS_SUCCESS";
export const FETCH_LIST_DATA_SUCCESS = "FETCH_LIST_DATA_SUCCESS";
export const FETCH_DATASET_SUCCESS = "FETCH_DATASET_SUCCESS";

export const SET_PAGINATION = "SET_PAGINATION";

export const SET_ADV_MATCHED_LOOKUP = "SET_ADV_MATCHED_LOOKUP";
export const SET_MATCHED_LOOKUP = "SET_MATCHED_LOOKUP";
export const TOGGLE_COLUMN_ISMAPPING = "TOGGLE_COLUMN_ISMAPPING";
export const TOGGLE_FILTER_ISMAPPING = "TOGGLE_FILTER_ISMAPPING";
export const CREATE_HOR_GROUPBYDATA = "CREATE_HOR_GROUPBYDATA";
export const CHANGE_HORIZONTAL_GROUPBY = "CHANGE_HORIZONTAL_GROUPBY";

export const SELECTED_FILTER_VALUE = "SELECTED_FILTER_VALUE";
export const ADD_ADDITIONAL_FILTER = "ADD_ADDITIONAL_FILTER";
export const SET_DROPDOWN_CHECKED = "SET_DROPDOWN_CHECKED";
export const SET_MULTISELECT_CHECKED = "SET_MULTISELECT_CHECKED";
export const SET_ADV_MULTISELECT_CHECKED = "SET_ADV_MULTISELECT_CHECKED";
export const SET_ADV_DROPDOWN_CHECKED = "SET_ADV_DROPDOWN_CHECKED";

export const REMOVE_ALL_FILTER = "REMOVE_ALL_FILTER";
export const REMOVE_QUICK_FILTER = "REMOVE_QUICK_FILTER";
export const REMOVE_ADVANCED_FILTER = "REMOVE_ADVANCED_FILTER";

export const QUICK_TEXT_VALUE = "QUICK_TEXT_VALUE";
export const RESET_QUICK_FILTER_VALUES = "RESET_QUICK_FILTER_VALUES";

export const CREATE_NEW_DATASET = "CREATE_NEW_DATASET";
export const EDIT_DATASET = "EDIT_DATASET";
export const GET_NEW_DATASET_INFO_SUCCESS = "GET_NEW_DATASET_INFO_SUCCESS";
export const DELETE_DATASET_DB = "DELETE_DATASET_DB";

export const SORTED_COLUMN = "SORTED_COLUMN";
export const SET_COLUMN_SEQ = "SET_COLUMN_SEQ";
export const SET_NEW_LAYOUT = "SET_NEW_LAYOUT";
