export const IMP_HIS_FETCH_ENTITY_DATA_SUCCESS =
  "IMP_HIS_FETCH_ENTITY_DATA_SUCCESS";
export const IMP_HIS_SELECT_NEW_ENTITY = "IMP_HIS_SELECT_NEW_ENTITY";

export const IMP_HIS_FETCH_MASTER_DATA_SUCCESS =
  "IMP_HIS_FETCH_MASTER_DATA_SUCCESS";
export const IMP_HIS_FETCH_LIST_FIELDS_SUCCESS =
  "IMP_HIS_FETCH_LIST_FIELDS_SUCCESS";
export const IMP_HIS_FETCH_LIST_DATA_SUCCESS =
  "IMP_HIS_FETCH_LIST_DATA_SUCCESS";
export const IMP_HIS_FETCH_DATASET_SUCCESS = "IMP_HIS_FETCH_DATASET_SUCCESS";

export const IMP_HIS_SET_PAGINATION = "IMP_HIS_SET_PAGINATION";
export const IMP_HIS_SET_PAGE_SIZE = "IMP_HIS_SET_PAGE_SIZE";
export const IMP_HIS_INCREMENT_COUNT = "IMP_HIS_INCREMENT_COUNT";
export const IMP_HIS_SET_DATASETID = "IMP_HIS_SET_DATASETID";
export const IMP_HIS_SET_ADV_MATCHED_LOOKUP = "IMP_HIS_SET_ADV_MATCHED_LOOKUP";
export const IMP_HIS_SET_MATCHED_LOOKUP = "IMP_HIS_SET_MATCHED_LOOKUP";
export const IMP_HIS_TOGGLE_COLUMN_ISMAPPING =
  "IMP_HIS_TOGGLE_COLUMN_ISMAPPING";
export const IMP_HIS_TOGGLE_FILTER_ISMAPPING =
  "IMP_HIS_TOGGLE_FILTER_ISMAPPING";
export const IMP_HIS_CREATE_HOR_GROUPBYDATA = "IMP_HIS_CREATE_HOR_GROUPBYDATA";
export const IMP_HIS_CHANGE_HORIZONTAL_GROUPBY =
  "IMP_HIS_CHANGE_HORIZONTAL_GROUPBY";

export const IMP_HIS_SELECTED_FILTER_VALUE = "IMP_HIS_SELECTED_FILTER_VALUE";
export const IMP_HIS_ADD_ADDITIONAL_FILTER = "IMP_HIS_ADD_ADDITIONAL_FILTER";
export const IMP_HIS_SET_DROPDOWN_CHECKED = "IMP_HIS_SET_DROPDOWN_CHECKED";
export const IMP_HIS_SET_MULTISELECT_CHECKED =
  "IMP_HIS_SET_MULTISELECT_CHECKED";
export const IMP_HIS_SET_ADV_MULTISELECT_CHECKED =
  "IMP_HIS_SET_ADV_MULTISELECT_CHECKED";
export const IMP_HIS_SET_ADV_DROPDOWN_CHECKED =
  "IMP_HIS_SET_ADV_DROPDOWN_CHECKED";

export const IMP_HIS_REMOVE_ALL_FILTER = "IMP_HIS_REMOVE_ALL_FILTER";
export const IMP_HIS_REMOVE_QUICK_FILTER = "IMP_HIS_REMOVE_QUICK_FILTER";
export const IMP_HIS_REMOVE_ADVANCED_FILTER = "IMP_HIS_REMOVE_ADVANCED_FILTER";

export const IMP_HIS_QUICK_TEXT_VALUE = "IMP_HIS_QUICK_TEXT_VALUE";
export const IMP_HIS_RESET_QUICK_FILTER_VALUES =
  "IMP_HIS_RESET_QUICK_FILTER_VALUES";

export const IMP_HIS_CREATE_NEW_DATASET = "IMP_HIS_CREATE_NEW_DATASET";
export const IMP_HIS_EDIT_DATASET = "IMP_HIS_EDIT_DATASET";
export const IMP_HIS_GET_NEW_DATASET_INFO_SUCCESS =
  "IMP_HIS_GET_NEW_DATASET_INFO_SUCCESS";
export const IMP_HIS_DELETE_DATASET_DB = "IMP_HIS_DELETE_DATASET_DB";

export const IMP_HIS_SORTED_COLUMN = "IMP_HIS_SORTED_COLUMN";
export const IMP_HIS_SET_COLUMN_SEQ = "IMP_HIS_SET_COLUMN_SEQ";
export const IMP_HIS_SET_NEW_LAYOUT = "IMP_HIS_SET_NEW_LAYOUT";
export const IMP_HIS_SET_DATEPICKER_VALUE = "IMP_HIS_SET_DATEPICKER_VALUE";
export const IMP_HIS_SET_WEEKFILTER_VALUE = "IMP_HIS_SET_WEEKFILTER_VALUE";
export const IMP_HIS_RESET_DATE_FILTERS = "IMP_HIS_RESET_DATE_FILTERS";
export const IMP_HIS_CHANGE_MASTER_DATA = "IMP_HIS_CHANGE_MASTER_DATA";
export const IMP_HIS_GET_USERNAME = "IMP_HIS_GET_USERNAME";
export const IMP_HIS_SET_LOADING = "IMP_HIS_SET_LOADING";
