export const PROJECT_FETCH_ENTITY_DATA_SUCCESS =
  "PROJECT_FETCH_ENTITY_DATA_SUCCESS";
export const PROJECT_SELECT_NEW_ENTITY = "PROJECT_SELECT_NEW_ENTITY";

export const PROJECT_FETCH_MASTER_DATA_SUCCESS =
  "PROJECT_FETCH_MASTER_DATA_SUCCESS";
export const PROJECT_FETCH_LIST_FIELDS_SUCCESS =
  "PROJECT_FETCH_LIST_FIELDS_SUCCESS";
export const PROJECT_FETCH_LIST_DATA_SUCCESS =
  "PROJECT_FETCH_LIST_DATA_SUCCESS";
export const PROJECT_FETCH_DATASET_SUCCESS = "PROJECT_FETCH_DATASET_SUCCESS";

export const PROJECT_SET_PAGINATION = "PROJECT_SET_PAGINATION";
export const PROJECT_SET_PAGE_SIZE = "PROJECT_SET_PAGE_SIZE";
export const PROJECT_INCREMENT_COUNT = "PROJECT_INCREMENT_COUNT";
export const PROJECT_SET_DATASETID = "PROJECT_SET_DATASETID";

export const PROJECT_SET_ADV_MATCHED_LOOKUP = "PROJECT_SET_ADV_MATCHED_LOOKUP";
export const PROJECT_SET_MATCHED_LOOKUP = "PROJECT_SET_MATCHED_LOOKUP";
export const PROJECT_TOGGLE_COLUMN_ISMAPPING =
  "PROJECT_TOGGLE_COLUMN_ISMAPPING";
export const PROJECT_TOGGLE_FILTER_ISMAPPING =
  "PROJECT_TOGGLE_FILTER_ISMAPPING";
export const PROJECT_CREATE_HOR_GROUPBYDATA = "PROJECT_CREATE_HOR_GROUPBYDATA";
export const PROJECT_CREATE_HOR_GROUPBYDATA_DIRECTION =
  "PROJECT_CREATE_HOR_GROUPBYDATA_DIRECTION";
export const PROJECT_CHANGE_HORIZONTAL_GROUPBY =
  "PROJECT_CHANGE_HORIZONTAL_GROUPBY";

export const PROJECT_SELECTED_FILTER_VALUE = "PROJECT_SELECTED_FILTER_VALUE";
export const PROJECT_ADD_ADDITIONAL_FILTER = "PROJECT_ADD_ADDITIONAL_FILTER";
export const PROJECT_SET_DROPDOWN_CHECKED = "PROJECT_SET_DROPDOWN_CHECKED";
export const PROJECT_SET_MULTISELECT_CHECKED =
  "PROJECT_SET_MULTISELECT_CHECKED";
export const PROJECT_SET_ADV_MULTISELECT_CHECKED =
  "PROJECT_SET_ADV_MULTISELECT_CHECKED";
export const PROJECT_SET_ADV_DROPDOWN_CHECKED =
  "PROJECT_SET_ADV_DROPDOWN_CHECKED";

export const PROJECT_REMOVE_ALL_FILTER = "PROJECT_REMOVE_ALL_FILTER";
export const PROJECT_REMOVE_QUICK_FILTER = "PROJECT_REMOVE_QUICK_FILTER";
export const PROJECT_REMOVE_ADVANCED_FILTER = "PROJECT_REMOVE_ADVANCED_FILTER";

export const PROJECT_QUICK_TEXT_VALUE = "PROJECT_QUICK_TEXT_VALUE";
export const PROJECT_RESET_QUICK_FILTER_VALUES =
  "PROJECT_RESET_QUICK_FILTER_VALUES";

export const PROJECT_CREATE_NEW_DATASET = "PROJECT_CREATE_NEW_DATASET";
export const PROJECT_EDIT_DATASET = "PROJECT_EDIT_DATASET";
export const PROJECT_GET_NEW_DATASET_INFO_SUCCESS =
  "PROJECT_GET_NEW_DATASET_INFO_SUCCESS";
export const PROJECT_DELETE_DATASET_DB = "PROJECT_DELETE_DATASET_DB";

export const PROJECT_SORTED_COLUMN = "PROJECT_SORTED_COLUMN";
export const PROJECT_SET_COLUMN_SEQ = "PROJECT_SET_COLUMN_SEQ";
export const PROJECT_SET_NEW_LAYOUT = "PROJECT_SET_NEW_LAYOUT";
export const PROJECT_SET_DATEPICKER_VALUE = "PROJECT_SET_DATEPICKER_VALUE";
export const PROJECT_SET_WEEKFILTER_VALUE = "PROJECT_SET_WEEKFILTER_VALUE";
export const PROJECT_RESET_DATE_FILTERS = "PROJECT_RESET_DATE_FILTERS";
export const PROJECT_CHANGE_MASTER_DATA = "PROJECT_CHANGE_MASTER_DATA";
export const PROJECT_GET_USERNAME = "PROJECT_GET_USERNAME";
export const PROJECT_SET_LOADING = "PROJECT_SET_LOADING";
export const PROJECT_EDIT_CELL = "PROJECT_EDIT_CELL";
export const PROJECT_RESET_EDIT_CELL = "PROJECT_RESET_EDIT_CELL";
export const PROJECT_SET_CURRENTPAGE = "PROJECT_SET_CURRENTPAGE";
