export const totalColumns = [
  {
    attributeid: "30010",
    displayapiname: "Title",
    ismapped: true,
    seqno: 10,
    screenfieldid: 40010,
    dataindex: "Title",
    visible: true,
    istitle: true,
    columnwidth: 300,
    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30020",
    displayapiname: "Chunk",
    ismapped: true,
    seqno: 20,
    screenfieldid: 40011,
    dataindex: "Chunk",
    visible: true,
    istitle: false,
    columnwidth: 125,
    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30030",
    displayapiname: "Project",
    ismapped: true,
    seqno: 30,
    screenfieldid: 40012,
    dataindex: "Project",
    visible: true,
    istitle: false,
    columnwidth: 160,
    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30040",
    displayapiname: "Due Date",
    ismapped: true,
    seqno: 40,
    screenfieldid: 40013,
    dataindex: "DueDate",
    visible: true,
    istitle: false,
    columnwidth: 100,
    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30050",
    displayapiname: "Priority",
    ismapped: true,
    seqno: 50,
    screenfieldid: 40014,
    dataindex: "Priority",
    visible: true,
    istitle: false,
    columnwidth: 80,

    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30060",
    displayapiname: "D1",
    ismapped: true,
    seqno: 60,
    screenfieldid: 40015,
    dataindex: "D1",
    visible: true,
    istitle: false,
    columnwidth: 150,
    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30070",
    displayapiname: "D2",
    ismapped: true,
    seqno: 70,
    screenfieldid: 40016,
    dataindex: "D2",
    visible: true,
    istitle: false,
    columnwidth: 150,
    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30080",
    displayapiname: "D3",
    ismapped: true,
    seqno: 80,
    screenfieldid: 40017,
    dataindex: "D3",
    visible: true,
    istitle: false,
    columnwidth: 150,
    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30090",
    displayapiname: "D4",
    ismapped: true,
    seqno: 90,
    screenfieldid: 40018,
    dataindex: "D4",
    visible: true,
    istitle: false,
    columnwidth: 150,
    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30100",
    displayapiname: "D5",
    ismapped: true,
    seqno: 100,
    screenfieldid: 40019,
    dataindex: "D5",
    visible: true,
    istitle: false,
    columnwidth: 150,
    //cellTemplate: "isTitleTemplate",
  },
  {
    attributeid: "30110",
    displayapiname: "D6",
    ismapped: true,
    seqno: 110,
    screenfieldid: 40020,
    dataindex: "D6",
    visible: true,
    istitle: false,
    columnwidth: 150,
    //cellTemplate: "isTitleTemplate",
  },
];
