export const Data = [
  {
    icds_entity_id: 7135,
    logical_name: "utbl_control1",
    Title: "Sales tech stack optimize",
    Chunk: "Working Session",
    Project: "2023 Sales Adhoc",
    DueDate: "07/28/2023",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7136,
    logical_name: "utbl_control2",
    Title: "ZoomInfo search",
    Chunk: "Working Session",
    Project: "2023 Operations Adhoc",
    DueDate: "07/2/2023",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7137,
    logical_name: "utbl_control3",
    Title: "CRM customer list clean up",
    Chunk: "Working Session",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2023",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7138,
    logical_name: "utbl_control4",
    Title: "SBO-Case Studies for deals completed",
    Chunk: "Insights",
    Project: "Project SaasBuyout",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7139,
    logical_name: "utbl_control5",
    Title: "SBO-Business Model",
    Chunk: "Insights",
    Project: "Project SaasBuyout",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7140,
    logical_name: "utbl_control6",
    Title: "SBO-DRS link research",
    Chunk: "Insights",
    Project: "Project SaasBuyout",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7141,
    logical_name: "utbl_control7",
    Title:
      "bMobile Sales Site Down / Root cause / how to avoid in future / Action Plan",
    Chunk: "Insight",
    Project: "2024 BUOPS",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7142,
    logical_name: "utbl_control8",
    Title: "HP - Managed Servers",
    Chunk: "Initiatives",
    Project: "2024 BUOPS",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7143,
    logical_name: "utbl_control9",
    Title: "Reporting From Arc CRM - Sales Data",
    Chunk: "Initiatives",
    Project: "2024 BUOPS",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7144,
    logical_name: "utbl_control10",
    Title: "Which Data Available / Where / How do we know?",
    Chunk: "Initiatives",
    Project: "2024 OPSDesign",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7145,
    logical_name: "utbl_control11",
    Title: "Account Mgmt",
    Chunk: "Initiatives",
    Project: "2024 OPSDesign",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7146,
    logical_name: "utbl_control12",
    Title: "Business Results",
    Chunk: "Initiatives",
    Project: "2024 OPSDesign",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7147,
    logical_name: "utbl_control13",
    Title: "Amazon Seller",
    Chunk: "Initiatives",
    Project: "2024 VTS Adhoc",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7148,
    logical_name: "utbl_control14",
    Title: "Trainer Hispanic / Consultant",
    Chunk: "Initiatives",
    Project: "2023 CMS Adhoc",
    DueDate: "09/15/2024",
    Priority: "D",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7149,
    logical_name: "utbl_control15",
    Title: "Known Source / Permanent Address Lease Cheap",
    Chunk: "House",
    Project: "FL Move",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7150,
    logical_name: "utbl_control16",
    Title:
      "2 week stay each in 3 places St Pete/Tampa, Sarasota, WestPalm Beach",
    Chunk: "House",
    Project: "FL Move",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7151,
    logical_name: "utbl_control17",
    Title: "Sub Lease or Apartment ?",
    Chunk: "House",
    Project: "FL Move",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7152,
    logical_name: "utbl_control18",
    Title: "Domicile Work - Detailed Plan",
    Chunk: "GRC",
    Project: "FL Move",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7153,
    logical_name: "utbl_control19",
    Title: "federal form for operating bank account",
    Chunk: "GRC",
    Project: "FL Move",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7154,
    logical_name: "utbl_control20",
    Title: "Domicile Audits",
    Chunk: "GRC",
    Project: "FL Move",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7155,
    logical_name: "utbl_control21",
    Title: "Monitor - Bank Balances & Treasury Transactions",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7156,
    logical_name: "utbl_control22",
    Title: "Validate and followup Bank Transfers",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7157,
    logical_name: "utbl_control23",
    Title: "Validate Online & CC Payments",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7158,
    logical_name: "utbl_control24",
    Title: "Monitor - AR Deposits",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7159,
    logical_name: "utbl_control25",
    Title: "BOD Call",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7160,
    logical_name: "utbl_control26",
    Title: "AP Validation",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7161,
    logical_name: "utbl_control27",
    Title: "Monitor - Bank Balances & Treasury Transactions",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7162,
    logical_name: "utbl_control28",
    Title: "Validate and followup Bank Transfers",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7163,
    logical_name: "utbl_control29",
    Title: "Validate Online & CC Payments",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7164,
    logical_name: "utbl_control30",
    Title: "Monitor - AR Deposits",
    Chunk: "General",
    Project: "2023 Finance Adhoc",
    DueDate: "02/1/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7165,
    logical_name: "utbl_control31",
    Title: "RCM-LG NPI Tracker on Data Scrape 95 Items",
    Chunk: "Execution",
    Project: "2024 VTS Adhoc",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7166,
    logical_name: "utbl_control32",
    Title: "RCM-LG NPI Tracker on Audit with the Data Scrape 66 Items",
    Chunk: "Execution",
    Project: "2024 VTS Adhoc",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7167,
    logical_name: "utbl_control33",
    Title: "Product Release Plan and Approval meeting",
    Chunk: "Execution",
    Project: "2023 Operations Pipeline",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7168,
    logical_name: "utbl_control34",
    Title: "COO Reporting",
    Chunk: "Execution",
    Project: "2023 Operations Pipeline",
    DueDate: "09/15/2024",
    Priority: "C",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7169,
    logical_name: "utbl_control35",
    Title: "ByDept2Sales",
    Chunk: "Execution",
    Project: "By Dept2",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7170,
    logical_name: "utbl_control36",
    Title: "All BU Contract Employee detail, Working hours",
    Chunk: "Execution",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2024",
    Priority: "C",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7171,
    logical_name: "utbl_control37",
    Title: "STS Check dealer list  Elaine",
    Chunk: "Execution",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7172,
    logical_name: "utbl_control38",
    Title: "Hexnode pricing",
    Chunk: "Execution",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7173,
    logical_name: "utbl_control39",
    Title: "HR Siva R&R",
    Chunk: "Execution",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2024",
    Priority: "C",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7174,
    logical_name: "utbl_control40",
    Title: "BEM Projects",
    Chunk: "Execution",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2024",
    Priority: "C",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7175,
    logical_name: "utbl_control41",
    Title: "ALL BU High level plan task - April",
    Chunk: "Execution",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2024",
    Priority: "C",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7176,
    logical_name: "utbl_control42",
    Title: "Tom KT plan",
    Chunk: "Execution",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2024",
    Priority: "B",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7177,
    logical_name: "utbl_control43",
    Title: "Ravi/Munib CMS Release Notes process",
    Chunk: "Execution",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
  {
    icds_entity_id: 7178,
    logical_name: "utbl_control44",
    Title: "Weekly summary report VTS leads",
    Chunk: "Execution",
    Project: "2023 Operations Adhoc",
    DueDate: "09/15/2024",
    Priority: "A",
    D1: false,
    D2: false,
    D3: false,
    D4: false,
    D5: false,
    D6: false,
  },
];
