export const PLAN_FETCH_PLAN_DATA_SUCCESS = "PLAN_FETCH_PLAN_DATA_SUCCESS";
export const PLAN_SELECT_NEW_ENTITY = "PLAN_SELECT_NEW_ENTITY";

export const PLAN_FETCH_MASTER_DATA_SUCCESS = "PLAN_FETCH_MASTER_DATA_SUCCESS";
export const PLAN_FETCH_SUB_MASTER_DATA_SUCCESS =
  "PLAN_FETCH_SUB_MASTER_DATA_SUCCESS";
export const PLAN_FETCH_LIST_FIELDS_SUCCESS = "PLAN_FETCH_LIST_FIELDS_SUCCESS";
export const PLAN_FETCH_LIST_DATA_SUCCESS = "PLAN_FETCH_LIST_DATA_SUCCESS";
export const PLAN_FETCH_DATASET_SUCCESS = "PLAN_FETCH_DATASET_SUCCESS";

export const PLAN_SET_PAGINATION = "PLAN_SET_PAGINATION";
export const PLAN_SET_PAGE_SIZE = "PLAN_SET_PAGE_SIZE";
export const PLAN_INCREMENT_COUNT = "PLAN_INCREMENT_COUNT";
export const PLAN_SET_DATASETID = "PLAN_SET_DATASETID";

export const PLAN_SET_ADV_MATCHED_LOOKUP = "PLAN_SET_ADV_MATCHED_LOOKUP";
export const PLAN_SET_MATCHED_LOOKUP = "PLAN_SET_MATCHED_LOOKUP";
export const PLAN_TOGGLE_COLUMN_ISMAPPING = "PLAN_TOGGLE_COLUMN_ISMAPPING";
export const PLAN_TOGGLE_FILTER_ISMAPPING = "PLAN_TOGGLE_FILTER_ISMAPPING";
export const PLAN_CREATE_HOR_GROUPBYDATA = "PLAN_CREATE_HOR_GROUPBYDATA";
export const PLAN_CHANGE_HORIZONTAL_GROUPBY = "PLAN_CHANGE_HORIZONTAL_GROUPBY";

export const PLAN_SELECTED_FILTER_VALUE = "PLAN_SELECTED_FILTER_VALUE";
export const PLAN_ADD_ADDITIONAL_FILTER = "PLAN_ADD_ADDITIONAL_FILTER";
export const PLAN_SET_DROPDOWN_CHECKED = "PLAN_SET_DROPDOWN_CHECKED";
export const PLAN_SET_MULTISELECT_CHECKED = "PLAN_SET_MULTISELECT_CHECKED";
export const PLAN_SET_ADV_MULTISELECT_CHECKED =
  "PLAN_SET_ADV_MULTISELECT_CHECKED";
export const PLAN_SET_ADV_DROPDOWN_CHECKED = "PLAN_SET_ADV_DROPDOWN_CHECKED";

export const PLAN_REMOVE_ALL_FILTER = "PLAN_REMOVE_ALL_FILTER";
export const PLAN_REMOVE_QUICK_FILTER = "PLAN_REMOVE_QUICK_FILTER";
export const PLAN_REMOVE_ADVANCED_FILTER = "PLAN_REMOVE_ADVANCED_FILTER";

export const PLAN_QUICK_TEXT_VALUE = "PLAN_QUICK_TEXT_VALUE";
export const PLAN_RESET_QUICK_FILTER_VALUES = "PLAN_RESET_QUICK_FILTER_VALUES";

export const PLAN_CREATE_NEW_DATASET = "PLAN_CREATE_NEW_DATASET";
export const PLAN_EDIT_DATASET = "PLAN_EDIT_DATASET";
export const PLAN_GET_NEW_DATASET_INFO_SUCCESS =
  "PLAN_GET_NEW_DATASET_INFO_SUCCESS";
export const PLAN_DELETE_DATASET_DB = "PLAN_DELETE_DATASET_DB";

export const PLAN_SORTED_COLUMN = "PLAN_SORTED_COLUMN";
export const PLAN_SET_COLUMN_SEQ = "PLAN_SET_COLUMN_SEQ";
export const PLAN_SET_NEW_LAYOUT = "PLAN_SET_NEW_LAYOUT";

export const PLAN_SET_DATEPICKER_VALUE = "PLAN_SET_DATEPICKER_VALUE";
export const PLAN_SET_WEEKFILTER_VALUE = "PLAN_SET_WEEKFILTER_VALUE";

export const PLAN_RESET_DATE_FILTERS = "PLAN_RESET_DATE_FILTERS ";
export const PLAN_CHANGE_MASTER_DATA = "PLAN_CHANGE_MASTER_DATA ";

export const PLAN_GET_USERNAME = "PLAN_GET_USERNAME ";
export const PLAN_SET_LOADING = "PLAN_SET_LOADING ";
export const PLAN_SET_TRANSACTIONID = "PLAN_SET_TRANSACTIONID ";
export const PLAN_360_FETCH_LIST_FIELDS_SUCCESS =
  "PLAN_360_FETCH_LIST_FIELDS_SUCCESS ";
export const PLAN_360_TASK_ROW_DATA = "PLAN_360_TASK_ROW_DATA ";
export const PLAN_360_DATASET_SUCCESS = "PLAN_360_DATASET_SUCCESS ";
export const PLAN_360_FETCH_SUB_LIST_FIELDS_SUCCESS =
  "PLAN_360_FETCH_SUB_LIST_FIELDS_SUCCESS ";
export const PLAN_360_SUB_TASK_ROW_DATA = "PLAN_360_SUB_TASK_ROW_DATA ";
export const PLAN_360_SUB_DATASET_SUCCESS = "PLAN_360_SUB_DATASET_SUCCESS ";

export const PLAN_PLANNED_WEEK = "PLAN_PLANNED_WEEK ";
export const PLAN_ASSIGNED_TO = "PLAN_ASSIGNED_TO ";
export const PLAN_INSERT_PLAN = "PLAN_INSERT_PLAN ";
export const PLAN_RESET_INSERT_PLAN = "PLAN_RESET_INSERT_PLAN ";

export const PLAN_SET_CURRENTPAGE = "PLAN_SET_CURRENTPAGE";
