export const TASKINFO_FETCH_ENTITY_DATA_SUCCESS =
  "TASKINFO_FETCH_ENTITY_DATA_SUCCESS";
export const TASKINFO_SELECT_NEW_ENTITY = "TASKINFO_SELECT_NEW_ENTITY";

export const TASKINFO_FETCH_MASTER_DATA_SUCCESS =
  "TASKINFO_FETCH_MASTER_DATA_SUCCESS";
export const TASKINFO_FETCH_LIST_FIELDS_SUCCESS =
  "TASKINFO_FETCH_LIST_FIELDS_SUCCESS";
export const TASKINFO_FETCH_LIST_DATA_SUCCESS =
  "TASKINFO_FETCH_LIST_DATA_SUCCESS";
export const TASKINFO_FETCH_DATASET_SUCCESS = "TASKINFO_FETCH_DATASET_SUCCESS";

export const TASKINFO_SET_PAGINATION = "TASKINFO_SET_PAGINATION";
export const TASKINFO_SET_PAGE_SIZE = "TASKINFO_SET_PAGE_SIZE";
export const TASKINFO_INCREMENT_COUNT = "TASKINFO_INCREMENT_COUNT";
export const TASKINFO_SET_DATASETID = "TASKINFO_SET_DATASETID";

export const TASKINFO_SET_ADV_MATCHED_LOOKUP =
  "TASKINFO_SET_ADV_MATCHED_LOOKUP";
export const TASKINFO_SET_MATCHED_LOOKUP = "TASKINFO_SET_MATCHED_LOOKUP";
export const TASKINFO_TOGGLE_COLUMN_ISMAPPING =
  "TASKINFO_TOGGLE_COLUMN_ISMAPPING";
export const TASKINFO_TOGGLE_FILTER_ISMAPPING =
  "TASKINFO_TOGGLE_FILTER_ISMAPPING";
export const TASKINFO_CREATE_HOR_GROUPBYDATA =
  "TASKINFO_CREATE_HOR_GROUPBYDATA";
export const TASKINFO_CHANGE_HORIZONTAL_GROUPBY =
  "TASKINFO_CHANGE_HORIZONTAL_GROUPBY";

export const TASKINFO_SELECTED_FILTER_VALUE = "TASKINFO_SELECTED_FILTER_VALUE";
export const TASKINFO_ADD_ADDITIONAL_FILTER = "TASKINFO_ADD_ADDITIONAL_FILTER";
export const TASKINFO_SET_DROPDOWN_CHECKED = "TASKINFO_SET_DROPDOWN_CHECKED";
export const TASKINFO_SET_MULTISELECT_CHECKED =
  "TASKINFO_SET_MULTISELECT_CHECKED";
export const TASKINFO_SET_ADV_MULTISELECT_CHECKED =
  "TASKINFO_SET_ADV_MULTISELECT_CHECKED";
export const TASKINFO_SET_ADV_DROPDOWN_CHECKED =
  "TASKINFO_SET_ADV_DROPDOWN_CHECKED";

export const TASKINFO_REMOVE_ALL_FILTER = "TASKINFO_REMOVE_ALL_FILTER";
export const TASKINFO_REMOVE_QUICK_FILTER = "TASKINFO_REMOVE_QUICK_FILTER";
export const TASKINFO_REMOVE_ADVANCED_FILTER =
  "TASKINFO_REMOVE_ADVANCED_FILTER";

export const TASKINFO_QUICK_TEXT_VALUE = "TASKINFO_QUICK_TEXT_VALUE";
export const TASKINFO_RESET_QUICK_FILTER_VALUES =
  "TASKINFO_RESET_QUICK_FILTER_VALUES";

export const TASKINFO_CREATE_NEW_DATASET = "TASKINFO_CREATE_NEW_DATASET";
export const TASKINFO_EDIT_DATASET = "TASKINFO_EDIT_DATASET";
export const TASKINFO_GET_NEW_DATASET_INFO_SUCCESS =
  "TASKINFO_GET_NEW_DATASET_INFO_SUCCESS";
export const TASKINFO_DELETE_DATASET_DB = "TASKINFO_DELETE_DATASET_DB";

export const TASKINFO_SORTED_COLUMN = "TASKINFO_SORTED_COLUMN";
export const TASKINFO_SET_COLUMN_SEQ = "TASKINFO_SET_COLUMN_SEQ";
export const TASKINFO_SET_NEW_LAYOUT = "TASKINFO_SET_NEW_LAYOUT";
export const TASKINFO_SET_DATEPICKER_VALUE = "TASKINFO_SET_DATEPICKER_VALUE";
export const TASKINFO_SET_WEEKFILTER_VALUE = "TASKINFO_SET_WEEKFILTER_VALUE";
export const TASKINFO_RESET_DATE_FILTERS = "TASKINFO_RESET_DATE_FILTERS";
export const TASKINFO_CHANGE_MASTER_DATA = "TASKINFO_CHANGE_MASTER_DATA";
export const TASKINFO_GET_USERNAME = "TASKINFO_GET_USERNAME";
export const TASKINFO_SET_LOADING = "TASKINFO_SET_LOADING";
export const TASKINFO_EDIT_CELL = "TASKINFO_EDIT_CELL";
export const TASKINFO_RESET_EDIT_CELL = "TASKINFO_RESET_EDIT_CELL";
export const TASKINFO_RESETALL = "TASKINFO_RESETALL";
export const TASKINFO_SET_CURRENTPAGE = "TASKINFO_SET_CURRENTPAGE";
