/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react/prop-types */
// *******~ Import ~******** //
//? React
import React, { useState, useEffect } from "react";
//? Assets
import { useDispatch, useSelector } from "react-redux";
import { parseISO, format } from "date-fns";

//? Components
import WijmoPagination from "@/components/TaskComp/Wijmo/WijmoPagination";
import ArcDataNotFound from "@/components/arccomponents/ui-components/nodatafound/no-data-found";
import ListPageTableLoading from "@/modules/loading-skeleton/listpage-table-loading";
import {
  FlexGrid,
  FlexGridColumn,
  FlexGridCellTemplate,
} from "@grapecity/wijmo.react.grid";
import "@grapecity/wijmo.styles/wijmo.css";

//? CSS

//? Images
// import cardImg1 from "@/style/arcstyle/images/card1.png";
// import cardImg2 from "@/style/arcstyle/images/card2.png";

//? JSON File

//? Icons
import { MdOutlineSystemUpdateAlt } from "react-icons/md";
import { MdOutlineFileDownload } from "react-icons/md";
import { GrDocumentDownload } from "react-icons/gr";
import { useNavigate } from "react-router-dom";
import { BiSolidEditAlt } from "react-icons/bi";
import { FaEye } from "react-icons/fa";
// *******~ Import ~******** //

export const GridData = ({ GridData, GridBinding, LoadingState }) => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const [UpdateStatusshow, setUpdateStatusShow] = useState(false);
  const [SelectedRow, setSelectedRow] = useState(false);

  const PlanSummeryStateStatus = useSelector(
    (state) => state.PlanSummeryState.status
  );

  useEffect(() => {
    removeWijimoLicense();
  }, []);

  function removeWijimoLicense() {
    const removeEvaluationText = () => {
      const bodyElements = document.body.children;
      for (let i = bodyElements.length - 1; i >= 0; i--) {
        const body = bodyElements[i];
        if (
          body.innerText.includes("Wijmo Evaluation") ||
          body.innerText.includes("Wijmo license")
        ) {
          body.remove();
        }
      }
    };
    removeEvaluationText();
  }

  console.log(GridData);
  const [pageSize, setPageSize] = useState(15);
  const [currentPage, setCurrentPage] = useState(1);
  const paginationConfig = {
    pageSize,
    currentPage,
    totalLength: 23,
  };
  return (
    <React.Fragment>
      {GridData?.length === 0 && PlanSummeryStateStatus !== "loading" ? (
        <ArcDataNotFound Title={"Data not found"} />
      ) : null}
      {LoadingState ? (
        <ListPageTableLoading />
      ) : (
        <FlexGrid
          autoRowHeights={true}
          deferResizing={true}
          frozenColumns={1}
          itemsSource={GridData}
          allowSorting={true}
          className="list-data-table with-360-page custom-height"
          headersVisibility="Column"
          selectionMode="None"
        >
          <FlexGridColumn
            allowDragging={false}
            allowResizing={true}
            binding="Contact_fullname"
            header="ID"
            minWidth={110}
            isReadOnly={true}
            fixed
          >
            <FlexGridCellTemplate
              on
              cellType="Cell"
              template={(ctx) => {
                const fullName = ctx.item.Contact_fullname;
                const RowData = ctx.item;
                const TransactionID = ctx.item.id;
                const words = fullName && fullName.split(" ");
                const startWithLetter = words ? words[0].charAt(0) : "";
                const endWithLetter =
                  words && words.length > 1
                    ? words[words.length - 1].charAt(0)
                    : "";
                return (
                  <>
                    <div className="name-td new-name-td with-action-1">
                      <a style={{ textDecoration: "none" }}>
                        <div className="name-detail">
                          {/* <span>
                            {startWithLetter}
                            {endWithLetter}
                          </span> */}
                          <p title={fullName}>{fullName}</p>
                        </div>
                      </a>
                      <div className="action with-action-1">
                        <span title="Edit">
                          <BiSolidEditAlt />
                        </span>
                      </div>
                      <div className="action with-action-1">
                      <span title="View">
                            <FaEye />
                        </span>
                      </div>
                    </div>
                  </>
                );
              }}
            />
          </FlexGridColumn>

          {GridBinding.map((data, index) => (
            <FlexGridColumn
              key={index}
              binding={data.binding}
              header={data.header}
              minWidth={data.width}
              width={data.width}
              allowResizing={true}
              allowSorting={true}
              fixed
              isReadOnly={true}
            >
              <FlexGridCellTemplate
                on
                cellType="Cell"
                template={(ctx) => {
                  const GridValue = ctx.item.date;
                  const ActualValue = ctx?.item[data.binding];
                  // console.log(GridValue);
                  const formattedDate = ["", null].includes(GridValue)
                    ? "-"
                    : GridValue;

                    // x
                  return (
                    <>
                      <div className="name-td new-name-td-default without-cell-edit">
                        <span
                          className="default-value clickable"
                          style={priorityStyle}
                          title={
                            data.binding === "date"
                              ? formattedDate
                              : ActualValue || "-"
                          }
                          onClick={() => {
                            sessionStorage.setItem(
                              "Campaignname",
                              ctx.item?.campaignname
                            );
                            if (data.header == "Calls") {
                              sessionStorage.setItem("currentKey", "Calls");
                            } else {
                              sessionStorage.setItem("currentKey", "Email");
                            }
                            // sessionStorage.setItem("currentKey",)
                            console.log(ctx.item);
                            console.log(data);
                            navigate("/prospect360");
                          }}
                        >
                          {data.binding === "date"
                            ? formattedDate
                            : ActualValue || "-"}
                        </span>
                      </div>
                    </>
                  );
                }}
              />
            </FlexGridColumn>
          ))}
        </FlexGrid>
      )}
      <WijmoPagination
        loading={false}
        paginationConfig={paginationConfig}
        onPageChange={setCurrentPage}
        onPageSizeChange={setPageSize}
      />
    </React.Fragment>
  );
};

export const GridDataToday = [
  {
    id: "b04515b9-6c78-4e19-88b3-40ae78791a05",
    campaignname: "Spring Sale",
    calls: "7",
    emails: "7",
    task: "1",
    overduecalls: "7",
    overdue: "7",
  },
  {
    id: "d456efb0-6ab2-43a6-b3d1-3d9b9c6cf21a",
    campaignname: "Holiday Promotion",
    calls: "15",
    emails: "12",
    task: "6",
    overduecalls: "4",
    overdue: "2",
  },
  {
    id: "f32dc10a-a88e-4a31-90a7-7e3411c8f5e2",
    campaignname: "Winter Clearance",
    calls: "9",
    emails: "8",
    task: "8",
    overduecalls: "3",
    overdue: "5",
  },
  {
    id: "3a1b89c5-d045-43e4-82e1-991e48ecdf8f",
    campaignname: "New Product Launch",
    calls: "20",
    emails: "18",
    task: "8",
    overduecalls: "6",
    overdue: "7",
  },
  {
    id: "93fd0e75-ae34-4054-8a90-d4a1e34d5a64",
    campaignname: "Back to School",
    calls: "11",
    emails: "9",
    task: "3",
    overduecalls: "3",
    overdue: "4",
  },
  {
    id: "8c9f912d-69c6-4324-b2ed-07463b3493e4",
    campaignname: "Black Friday Sale",
    calls: "14",
    emails: "15",
    task: "7",
    overduecalls: "2",
    overdue: "3",
  },
  {
    id: "6d7b49cf-8b0a-4aef-a838-7c42ab3bdc27",
    campaignname: "Cyber Monday Deals",
    calls: "17",
    emails: "13",
    task: "6",
    overduecalls: "5",
    overdue: "6",
  },
  {
    id: "07be5bb3-5945-4f18-86b4-80a7e5678c14",
    campaignname: "Summer Discount",
    calls: "10",
    emails: "7",
    task: "9",
    overduecalls: "2",
    overdue: "1",
  },
  {
    id: "ea2a456f-47c6-4f29-828c-55a7d2d90d14",
    campaignname: "Valentine's Day Promo",
    calls: "12",
    emails: "14",
    task: "10",
    overduecalls: "3",
    overdue: "2",
  },
  {
    id: "c73e5ec4-bd6f-41b7-a4bc-d6ea1cb84adf",
    campaignname: "Anniversary Celebration",
    calls: "8",
    emails: "6",
    task: "11",
    overduecalls: "4",
    overdue: "5",
  },
  {
    id: "f12d90ad-77bf-4410-b5f3-eefdb83a472f",
    campaignname: "End of Season Sale",
    calls: "13",
    emails: "11",
    task: "20",
    overduecalls: "6",
    overdue: "4",
  },
  {
    id: "c8e437c5-519f-4b0a-bdf9-ef12d7ac02ad",
    campaignname: "Weekend Specials",
    calls: "16",
    emails: "10",
    task: "1",
    overduecalls: "4",
    overdue: "3",
  },
  {
    id: "7a5c4c8d-df5f-482f-9aa2-8d463e1973cf",
    campaignname: "Mega Clearance",
    calls: "18",
    emails: "17",
    task: "2",
    overduecalls: "7",
    overdue: "8",
  },
  {
    id: "ae4738f4-bc9d-468d-91b9-e5bfbe79d3c1",
    campaignname: "Special Offers Week",
    calls: "9",
    emails: "5",
    task: "17",
    overduecalls: "2",
    overdue: "3",
  },
  {
    id: "0c1e7a37-0c9f-497e-898f-68b2a6dc84e7",
    campaignname: "Flash Sale Event",
    calls: "11",
    emails: "12",
    task: "15",
    overduecalls: "5",
    overdue: "4",
  },
  {
    id: "5efb498c-4d96-40b1-a098-9cd3418f1f44",
    campaignname: "Exclusive Member Offers",
    calls: "10",
    emails: "9",
    task: "3",
    overduecalls: "3",
    overdue: "3",
  },
  {
    id: "d4a9a1dc-d580-4f0e-83e4-3b0ad5a1b2af",
    campaignname: "Referral Rewards",
    calls: "7",
    emails: "8",
    task: "5",
    overduecalls: "2",
    overdue: "1",
  },
  {
    id: "bdf77d96-731d-40ec-b6ab-3dbba92bf6f3",
    campaignname: "Loyalty Program Promo",
    calls: "14",
    emails: "11",
    task: "16",
    overduecalls: "4",
    overdue: "6",
  },
  {
    id: "3e80f5b8-b45f-4933-85a8-cbf4c6b7b14c",
    campaignname: "Discount Bonanza",
    calls: "20",
    emails: "18",
    task: "1",
    overduecalls: "8",
    overdue: "9",
  },
  {
    id: "aa3e1c5a-cc6d-4208-8bb1-0ed72d91b1c9",
    campaignname: "Festive Deals",
    calls: "19",
    emails: "17",
    task: "5",
    overduecalls: "7",
    overdue: "8",
  },
];
export const GridDataTomorrow = [
  {
    id: "0c1e7a37-0c9f-497e-898f-68b2a6dc84e7",
    campaignname: "Flash Sale Event",
    calls: "11",
    emails: "12",
    task: "1",
    overduecalls: "5",
    overdue: "4",
  },
  {
    id: "5efb498c-4d96-40b1-a098-9cd3418f1f44",
    campaignname: "Exclusive Member Offers",
    calls: "10",
    emails: "9",
    task: "21",
    overduecalls: "3",
    overdue: "3",
  },
  {
    id: "d4a9a1dc-d580-4f0e-83e4-3b0ad5a1b2af",
    campaignname: "Referral Rewards",
    calls: "7",
    emails: "8",
    task: "12",
    overduecalls: "2",
    overdue: "1",
  },
  {
    id: "bdf77d96-731d-40ec-b6ab-3dbba92bf6f3",
    campaignname: "Loyalty Program Promo",
    calls: "14",
    emails: "11",
    task: "11",
    overduecalls: "4",
    overdue: "6",
  },
  {
    id: "3e80f5b8-b45f-4933-85a8-cbf4c6b7b14c",
    campaignname: "Discount Bonanza",
    calls: "20",
    emails: "18",
    task: "5",
    overduecalls: "8",
    overdue: "9",
  },
  {
    id: "aa3e1c5a-cc6d-4208-8bb1-0ed72d91b1c9",
    campaignname: "Festive Deals",
    calls: "19",
    emails: "17",
    task: "7",
    overduecalls: "7",
    overdue: "8",
  },
];
export const GridDataOverdue = [
  {
    id: "f12d90ad-77bf-4410-b5f3-eefdb83a472f",
    campaignname: "End of Season Sale",
    calls: "13",
    emails: "11",
    task: "12",
    overduecalls: "6",
    overdue: "4",
  },
  {
    id: "c8e437c5-519f-4b0a-bdf9-ef12d7ac02ad",
    campaignname: "Weekend Specials",
    calls: "16",
    emails: "10",
    task: "14",
    overduecalls: "4",
    overdue: "3",
  },
  {
    id: "7a5c4c8d-df5f-482f-9aa2-8d463e1973cf",
    campaignname: "Mega Clearance",
    calls: "18",
    emails: "17",
    task: "1",
    overduecalls: "7",
    overdue: "8",
  },
  {
    id: "ae4738f4-bc9d-468d-91b9-e5bfbe79d3c1",
    campaignname: "Special Offers Week",
    calls: "9",
    emails: "5",
    task: "13",
    overduecalls: "2",
    overdue: "3",
  },
  {
    id: "0c1e7a37-0c9f-497e-898f-68b2a6dc84e7",
    campaignname: "Flash Sale Event",
    calls: "11",
    emails: "12",
    task: "6",
    overduecalls: "5",
    overdue: "4",
  },
  {
    id: "5efb498c-4d96-40b1-a098-9cd3418f1f44",
    campaignname: "Exclusive Member Offers",
    calls: "10",
    emails: "9",
    task: "9",
    overduecalls: "3",
    overdue: "3",
  },
  {
    id: "d4a9a1dc-d580-4f0e-83e4-3b0ad5a1b2af",
    campaignname: "Referral Rewards",
    calls: "7",
    emails: "8",
    task: "10",
    overduecalls: "2",
    overdue: "1",
  },
  {
    id: "bdf77d96-731d-40ec-b6ab-3dbba92bf6f3",
    campaignname: "Loyalty Program Promo",
    calls: "14",
    emails: "11",
    task: "12",
    overduecalls: "4",
    overdue: "6",
  },
  {
    id: "3e80f5b8-b45f-4933-85a8-cbf4c6b7b14c",
    campaignname: "Discount Bonanza",
    calls: "20",
    emails: "18",
    task: "17",
    overduecalls: "8",
    overdue: "9",
  },
  {
    id: "aa3e1c5a-cc6d-4208-8bb1-0ed72d91b1c9",
    campaignname: "Festive Deals",
    calls: "19",
    emails: "17",
    task: "12",
    overduecalls: "7",
    overdue: "8",
  },
];

export const GridBinding = [
  // { header: "Lead Name", binding: "Contact_fullname", width: 300 },
  { header: "Title", binding: "Contact_jobTitle", width: 150 },
  { header: "Priority", binding: "Contact_Email", width: 150 },
  { header: "Category", binding: "Contact_leadSourceCode_text", width: 150 },
  { header: "Type", binding: "Contact_CreatedBy_text", width: 150 },
  { header: "Phone", binding: "Contact_PhoneNumber", width: 150 },
  {
    header: "Status",
    binding: "Arc_WorkFlowStatus_Name_text",
    width: 150,
  },
  {
    header: "Created By",
    binding: "Arc_WorkFlowStages_Name_text",
    width: 150,
  },
  {
    header: "Assigned To",
    binding: "Arc_WorkFlowStages_Name_text",
    width: 150,
  },
  {
    header: "Last Modified",
    binding: "Arc_WorkFlowStages_Name_text",
    width: 150,
  },
];

export const LeadData = [
  {
    id: "a619c4ee-c268-45ca-928a-a7af70fe97eb",
    sid: "1344",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "1/3/2025 7:24:38 AM",
    tags: "",
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "System failure",
    Contact_fullname: "536524",
    Contact_Email: "Critical",
    Contact_PhoneNumber: "+918657890876",
    Contact_EmployeeId: "",
    accountId: "",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1027",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/13/2025 9:27:48 AM",
    CreatedBy: "1027",
    Contact_CreatedOn: "1/3/2025 7:24:38 AM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Anita",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "jame feror",
    Contact_LeadOwner_text: "Anita",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "24ed7d64-09c5-4bfb-886a-65c619438701",
    sid: "1342",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f504",
    createdon: "1/2/2025 9:54:10 AM",
    tags: '[{"name":"kezjch","colorcode":"6"}]',
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "UnQualified",
    Contact_jobTitle: "System Failure",
    Contact_fullname: "544338",
    Contact_Email: "High",
    Contact_PhoneNumber: "718-555-0122",
    Contact_EmployeeId: "",
    accountId: "4b4d99e1-b8d8-44db-be22-d35a1442171d",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "7658.99",
    Contact_Modifiedon: "1/8/2025 7:57:16 AM",
    CreatedBy: "1027",
    Contact_CreatedOn: "1/2/2025 9:54:10 AM",
    Contact_accountId_text: "Lambda Group11",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Anita",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "lamie yamal",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "2e13a9ee-19e0-4644-b00e-4366e96aca0c",
    sid: "1341",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "1/2/2025 9:53:03 AM",
    tags: '[{"name":"police","colorcode":"6"}]',
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "System failure",
    Contact_fullname: "567898",
    Contact_Email: "High",
    Contact_PhoneNumber: "7777888899",
    Contact_EmployeeId: "",
    accountId: "",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "asjdsa",
    Contact_address1Line2: "lkjsjkl",
    Contact_address1Line3: "",
    Contact_address1City: "chennai",
    Contact_address1StateOrProvince: "AK",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/9/2025 4:49:17 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "1/2/2025 9:53:03 AM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "Anthony Andre",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "cad58753-5c62-4fdf-8671-a0f520992f27",
    sid: "1340",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "1/2/2025 9:52:44 AM",
    tags: '[{"name":"qwerty","colorcode":"6"},{"name":"test","colorcode":"6"}]',
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "System failure",
    Contact_fullname: "583424",
    Contact_Email: "High",
    Contact_PhoneNumber: "7777888899",
    Contact_EmployeeId: "",
    accountId: "",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "asjdsa",
    Contact_address1Line2: "lkjsjkl",
    Contact_address1Line3: "",
    Contact_address1City: "chennai",
    Contact_address1StateOrProvince: "AK",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/9/2025 4:49:39 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "1/2/2025 9:52:44 AM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "Isabella Mohad",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "44d28ce3-8354-4b0f-9987-75abfb30c36e",
    sid: "1339",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f504",
    createdon: "1/2/2025 9:50:56 AM",
    tags: "",
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "UnQualified",
    Contact_jobTitle: "System failure",
    Contact_fullname: "590234",
    Contact_Email: "High",
    Contact_PhoneNumber: "1234567890",
    Contact_EmployeeId: "1234",
    accountId: "cccf0ab6-dfba-4709-9f80-346e5526c786",
    parentContactId: "71701a6a-cd75-4ec5-a633-321eafe5584c",
    leadSourceCode: "19000510740",
    customerTypeCode: "19000510735",
    customerSizeCode: "19000510730",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/13/2025 7:02:26 AM",
    CreatedBy: "1027",
    Contact_CreatedOn: "1/2/2025 9:50:56 AM",
    Contact_accountId_text: "ZenZone",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Anita",
    Contact_customerSizeCode_text: "Medium Business",
    Contact_customerTypeCode_text: "Existing Customer",
    Contact_department_text: "",
    Contact_id_text: "Amelia John",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "Alex Jensen",
  },
  {
    id: "7a3e48a8-4c3d-46f5-b075-d24a9697e454",
    sid: "1331",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f504",
    createdon: "12/19/2024 9:32:19 AM",
    tags: "",
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "UnQualified",
    Contact_jobTitle: "System failure",
    Contact_fullname: "542432",
    Contact_Email: "High",
    Contact_PhoneNumber: "+918637436501",
    Contact_EmployeeId: "",
    accountId: "",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "12000.00",
    Contact_Modifiedon: "12/19/2024 9:32:19 AM",
    CreatedBy: "1027",
    Contact_CreatedOn: "12/19/2024 9:32:19 AM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Anita",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "Amen shuf",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "d3f8bcf4-0184-410c-a22b-1ab4c4149c00",
    sid: "1323",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f503",
    createdon: "12/5/2024 11:03:28 AM",
    tags: '[{"name":"w","colorcode":"6"}]',
    Arc_WorkFlow_Name_text: "",
    Arc_WorkFlowStages_Name_text: "",
    Arc_WorkFlowStatus_Name_text: "",
    Contact_jobTitle: "System failure",
    Contact_fullname: "593423",
    Contact_Email: "Critical",
    Contact_PhoneNumber: "+919887678981w",
    Contact_EmployeeId: "snd",
    accountId: "5ddceac4-9d82-49f6-ae09-3ff4ec7a5473",
    parentContactId: "525e465a-9f3c-49c7-9e86-343a1602d1f6",
    leadSourceCode: "19000510741",
    customerTypeCode: "19000510737",
    customerSizeCode: "19000510730",
    preferredContactMethodCode: "19000510684",
    preferredServiceId: "19000510846",
    LeadOwner: "1016",
    Rating: "19000510814",
    paymentTermsCode: "19000510689",
    department: "19000510851",
    Contact_address1Line1: "32ffew",
    Contact_address1Line2: "swwe",
    Contact_address1Line3: "dede",
    Contact_address1City: "Chennai",
    Contact_address1StateOrProvince: "Tamil Nadu1",
    Contact_Country: "11",
    Contact_companyname: "2e",
    Contact_webSiteUrl: "www.tamil.com",
    Contact_description: "xed",
    Contact_annualIncome: "21.00",
    Contact_Modifiedon: "1/13/2025 5:34:19 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "12/5/2024 11:03:28 AM",
    Contact_accountId_text: "Vertex2a",
    Contact_paymentTermsCode_text: "2% 10, Net 30",
    Contact_preferredContactMethodCode_text: "Phone",
    Contact_preferredServiceId_text: "Maintenance Services",
    Contact_Rating_text: "Warm",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "Medium Business",
    Contact_customerTypeCode_text: "Former Customer",
    Contact_department_text: "IT",
    Contact_id_text: "Harper pope",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "Aiden Rivera",
  },
  {
    id: "f06cd43e-ebe8-42d7-8ef5-1097efe0b468",
    sid: "1322",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "12/5/2024 10:45:32 AM",
    tags: '[{"name":"hello","colorcode":"6"}]',
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "System failure",
    Contact_fullname: "524345",
    Contact_Email: "High",
    Contact_PhoneNumber: "+919887678981",
    Contact_EmployeeId: "21",
    accountId: "",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/13/2025 5:58:27 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "12/5/2024 10:45:32 AM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "James  Dean",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "81b66e86-3c2a-4b55-8969-a0a292d42f48",
    sid: "1321",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f502",
    createdon: "12/5/2024 10:40:41 AM",
    tags: '[{"name":"1","colorcode":"6"},{"name":"n","colorcode":"6"}]',
    Arc_WorkFlow_Name_text: "",
    Arc_WorkFlowStages_Name_text: "",
    Arc_WorkFlowStatus_Name_text: "",
    Contact_jobTitle: "System failure",
    Contact_fullname: "567435",
    Contact_Email: "High",
    Contact_PhoneNumber: "939221",
    Contact_EmployeeId: "1",
    accountId: "ed1f2d85-8d68-400a-9e34-3c28a7ee2756",
    parentContactId: "4c164457-8a2c-42b6-947a-ad052749f3d5",
    leadSourceCode: "19000510739",
    customerTypeCode: "19000510735",
    customerSizeCode: "19000510729",
    preferredContactMethodCode: "19000510685",
    preferredServiceId: "19000510845",
    LeadOwner: "1016",
    Rating: "19000510815",
    paymentTermsCode: "19000510691",
    department: "19000510850",
    Contact_address1Line1: "wesd1",
    Contact_address1Line2: "11",
    Contact_address1Line3: "iii1",
    Contact_address1City: "Chennai1",
    Contact_address1StateOrProvince: "Tamil Nadu1",
    Contact_Country: "1",
    Contact_companyname: "2e2",
    Contact_webSiteUrl: "www.tamil.com",
    Contact_description: "1",
    Contact_annualIncome: "211.00",
    Contact_Modifiedon: "1/9/2025 4:52:04 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "12/5/2024 10:40:41 AM",
    Contact_accountId_text: "Alpha Beta",
    Contact_paymentTermsCode_text: "Net 60",
    Contact_preferredContactMethodCode_text: "Fax",
    Contact_preferredServiceId_text: "Technical Support",
    Contact_Rating_text: "Cold",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "Small Business",
    Contact_customerTypeCode_text: "Existing Customer",
    Contact_department_text: "Marketing",
    Contact_id_text: "Henry  James",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "Alice Harris",
  },
  {
    id: "a1250223-0a05-47f5-bf56-934715846545",
    sid: "1320",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "12/4/2024 12:13:17 PM",
    tags: '[{"name":"sa","colorcode":"6"}]',
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "System failure",
    Contact_fullname: "598732",
    Contact_Email: "jofer@acme.com",
    Contact_PhoneNumber: "+919887678981",
    Contact_EmployeeId: "snd",
    accountId: "5ddceac4-9d82-49f6-ae09-3ff4ec7a5473",
    parentContactId: "d30fc376-401d-4082-a194-ead72bb8ad7d",
    leadSourceCode: "19000510741",
    customerTypeCode: "19000510734",
    customerSizeCode: "19000510730",
    preferredContactMethodCode: "19000510684",
    preferredServiceId: "19000510845",
    LeadOwner: "1016",
    Rating: "19000510815",
    paymentTermsCode: "19000510689",
    department: "19000510851",
    Contact_address1Line1: "we",
    Contact_address1Line2: "swew",
    Contact_address1Line3: "dsdds",
    Contact_address1City: "Chennai",
    Contact_address1StateOrProvince: "Tamil Nadu",
    Contact_Country: "india",
    Contact_companyname: "2e",
    Contact_webSiteUrl: "www.tamil.com",
    Contact_description: "xed",
    Contact_annualIncome: "21.00",
    Contact_Modifiedon: "1/9/2025 4:52:23 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "12/4/2024 12:13:17 PM",
    Contact_accountId_text: "Vertex2a",
    Contact_paymentTermsCode_text: "2% 10, Net 30",
    Contact_preferredContactMethodCode_text: "Phone",
    Contact_preferredServiceId_text: "Technical Support",
    Contact_Rating_text: "Cold",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "Medium Business",
    Contact_customerTypeCode_text: "New Customer",
    Contact_department_text: "IT",
    Contact_id_text: "William  Blake",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "Alfrdra william",
  },
  {
    id: "7575fe85-4c76-4c30-8241-75a30a13888e",
    sid: "1317",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "12/4/2024 5:22:12 AM",
    tags: "",
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "System failure",
    Contact_fullname: "589823",
    Contact_Email: "jofer@acme.com",
    Contact_PhoneNumber: "+919887678981",
    Contact_EmployeeId: "",
    accountId: "",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/13/2025 5:48:12 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "12/4/2024 5:22:12 AM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "Mary  Jane",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "0effee00-6ad9-44b6-b181-c174d1695e9c",
    sid: "1316",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "12/4/2024 5:21:07 AM",
    tags: "",
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "System failure",
    Contact_fullname: "Charles  Ray",
    Contact_Email: "jofer@acme.com",
    Contact_PhoneNumber: "21",
    Contact_EmployeeId: "",
    accountId: "",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/9/2025 4:53:20 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "12/4/2024 5:21:07 AM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "Charles  Ray",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "d750df1d-ba06-406a-9096-26cdf49a72ad",
    sid: "1315",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "12/3/2024 12:42:56 PM",
    tags: "",
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "www",
    Contact_fullname: "Elijah Mikealson",
    Contact_Email: "testcrm@innospire.com",
    Contact_PhoneNumber: "9635214454752",
    Contact_EmployeeId: "",
    accountId: "5eca5dc4-3158-40a2-a11d-70b3491d69ae",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/13/2025 9:38:44 AM",
    CreatedBy: "1027",
    Contact_CreatedOn: "12/3/2024 12:42:56 PM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Anita",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "Elijah Mikealson",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "7ea05ece-e4ba-4c3d-a892-82f264108690",
    sid: "1312",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "11/28/2024 11:54:09 AM",
    tags: "",
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "",
    Contact_fullname: "Thomas  Wayne",
    Contact_Email: "jofer@acme.com",
    Contact_PhoneNumber: "+919887678981",
    Contact_EmployeeId: "",
    accountId: "",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/9/2025 4:52:45 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "11/28/2024 11:54:09 AM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "Thomas  Wayne",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "be6c7569-bfdc-4320-886e-d12cd3716805",
    sid: "1311",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "11/28/2024 11:53:32 AM",
    tags: "",
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "",
    Contact_fullname: "Emma  Rose",
    Contact_Email: "jofer@acme.com",
    Contact_PhoneNumber: "+919887678981",
    Contact_EmployeeId: "",
    accountId: "",
    parentContactId: "",
    leadSourceCode: "0",
    customerTypeCode: "0",
    customerSizeCode: "0",
    preferredContactMethodCode: "0",
    preferredServiceId: "0",
    LeadOwner: "1016",
    Rating: "0",
    paymentTermsCode: "0",
    department: "0",
    Contact_address1Line1: "",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "",
    Contact_address1StateOrProvince: "",
    Contact_Country: "",
    Contact_companyname: "",
    Contact_webSiteUrl: "",
    Contact_description: "",
    Contact_annualIncome: "",
    Contact_Modifiedon: "1/9/2025 4:54:02 AM",
    CreatedBy: "1016",
    Contact_CreatedOn: "11/28/2024 11:53:32 AM",
    Contact_accountId_text: "",
    Contact_paymentTermsCode_text: "",
    Contact_preferredContactMethodCode_text: "",
    Contact_preferredServiceId_text: "",
    Contact_Rating_text: "",
    Contact_CreatedBy_text: "Annamalai",
    Contact_customerSizeCode_text: "",
    Contact_customerTypeCode_text: "",
    Contact_department_text: "",
    Contact_id_text: "Emma  Rose",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Incident Management",
    Contact_parentContactId_text: "",
  },
  {
    id: "95a212ed-92b4-4380-ad30-fd0cd19e2db5",
    sid: "1107",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "8/27/2024 12:28:58 AM",
    tags: "",
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "Procurement Manager",
    Contact_fullname: "Emma  Doe",
    Contact_Email: "john.doe1@example.com",
    Contact_PhoneNumber: "732-705-7771",
    Contact_EmployeeId: "EMP10606",
    accountId: "afbe4539-ad2e-4099-91c6-c29223e59909",
    parentContactId: "6bbed449-65e0-45a8-8ec0-9630420907e0",
    leadSourceCode: "19000510746",
    customerTypeCode: "19000510735",
    customerSizeCode: "19000510733",
    preferredContactMethodCode: "19000510686",
    preferredServiceId: "19000510848",
    LeadOwner: "1016",
    Rating: "19000510813",
    paymentTermsCode: "19000510690",
    department: "19000510855",
    Contact_address1Line1: "123 Data Lane",
    Contact_address1Line2: "Lab 2B",
    Contact_address1Line3: "",
    Contact_address1City: "San Francisco",
    Contact_address1StateOrProvince: "CA",
    Contact_Country: "USA",
    Contact_companyname: "JD Enterprises",
    Contact_webSiteUrl: "https://www.jdent.com",
    Contact_description: "Specialist in data analytics and AI",
    Contact_annualIncome: "180000.00",
    Contact_Modifiedon: "1/13/2025 8:01:05 AM",
    CreatedBy: "1010",
    Contact_CreatedOn: "8/27/2024 12:28:58 AM",
    Contact_accountId_text: "Beta Ltd",
    Contact_paymentTermsCode_text: "Net 45",
    Contact_preferredContactMethodCode_text: "Mail",
    Contact_preferredServiceId_text: "Custom Development",
    Contact_Rating_text: "Hot",
    Contact_CreatedBy_text: "Kiran",
    Contact_customerSizeCode_text: "Startup",
    Contact_customerTypeCode_text: "Existing Customer",
    Contact_department_text: "Research and Development",
    Contact_id_text: "Emma  Doe",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Partner",
    Contact_parentContactId_text: "Wil Wheaton",
  },
  {
    id: "0ee9bf8c-e0d6-49c8-bcac-fcdfed0f22a6",
    sid: "1106",
    WorkflowStageid: "1a3d1758-f4c1-47e0-85a9-d36078f8f301",
    WorkflowStatusid: "1a3d1758-f4c1-47e0-85a9-d36078f8f501",
    createdon: "8/27/2024 1:53:19 AM",
    tags: '[{"name":"hy","colorcode":"6"},{"name":"cvdf","colorcode":"6"},{"name":"nifty","colorcode":"6"}]',
    Arc_WorkFlow_Name_text: "Contact Life Cycle",
    Arc_WorkFlowStages_Name_text: "Lead",
    Arc_WorkFlowStatus_Name_text: "New",
    Contact_jobTitle: "Customer Service Manager",
    Contact_fullname: "Mrs. Wolowitzz",
    Contact_Email: "mrs.wolowitzz@example.com",
    Contact_PhoneNumber: "718-555-0122",
    Contact_EmployeeId: "EMPBBT21",
    accountId: "625608ca-1017-4e5f-b780-1c89829a58b9",
    parentContactId: "6bbed449-65e0-45a8-8ec0-9630420907e0",
    leadSourceCode: "19000510743",
    customerTypeCode: "19000510738",
    customerSizeCode: "19000510729",
    preferredContactMethodCode: "19000510682",
    preferredServiceId: "19000510848",
    LeadOwner: "1016",
    Rating: "19000510814",
    paymentTermsCode: "19000510691",
    department: "19000510856",
    Contact_address1Line1: "789 Queens Blvd",
    Contact_address1Line2: "",
    Contact_address1Line3: "",
    Contact_address1City: "New York",
    Contact_address1StateOrProvince: "NY",
    Contact_Country: "USA",
    Contact_companyname: "IFB Corporations",
    Contact_webSiteUrl: "https://www.mrswolowitz.com",
    Contact_description: "Howard’s overbearing mother",
    Contact_annualIncome: "65000.00",
    Contact_Modifiedon: "8/27/2024 1:53:19 AM",
    CreatedBy: "1015",
    Contact_CreatedOn: "8/27/2024 1:53:19 AM",
    Contact_accountId_text: "Poor Richard’s Pub",
    Contact_paymentTermsCode_text: "Net 60",
    Contact_preferredContactMethodCode_text: "Any",
    Contact_preferredServiceId_text: "Custom Development",
    Contact_Rating_text: "Warm",
    Contact_CreatedBy_text: "Aarthi",
    Contact_customerSizeCode_text: "Small Business",
    Contact_customerTypeCode_text: "VIP Customer",
    Contact_department_text: "Legal",
    Contact_id_text: "Mrs. Wolowitzz",
    Contact_LeadOwner_text: "Annamalai",
    Contact_leadSourceCode_text: "Trade Show",
    Contact_parentContactId_text: "Wil Wheaton",
  },
];
