export const EXPORTHISTORY_FETCH_EXPORTHISTORY_DATA_SUCCESS =
  "EXPORTHISTORY_FETCH_EXPORTHISTORY_DATA_SUCCESS";
export const EXPORTHISTORY_SELECT_NEW_ENTITY = "EXPORTHISTORY_SELECT_NEW_ENTITY";

export const EXPORTHISTORY_FETCH_MASTER_DATA_SUCCESS =
  "EXPORTHISTORY_FETCH_MASTER_DATA_SUCCESS";
export const EXPORTHISTORY_FETCH_SUB_MASTER_DATA_SUCCESS =
  "EXPORTHISTORY_FETCH_SUB_MASTER_DATA_SUCCESS";
export const EXPORTHISTORY_FETCH_LIST_FIELDS_SUCCESS =
  "EXPORTHISTORY_FETCH_LIST_FIELDS_SUCCESS";
export const EXPORTHISTORY_FETCH_LIST_DATA_SUCCESS =
  "EXPORTHISTORY_FETCH_LIST_DATA_SUCCESS";
export const EXPORTHISTORY_FETCH_DATASET_SUCCESS =
  "EXPORTHISTORY_FETCH_DATASET_SUCCESS";

export const EXPORTHISTORY_SET_PAGINATION = "EXPORTHISTORY_SET_PAGINATION";
export const EXPORTHISTORY_SET_PAGE_SIZE = "EXPORTHISTORY_SET_PAGE_SIZE";
export const EXPORTHISTORY_INCREMENT_COUNT = "EXPORTHISTORY_INCREMENT_COUNT";
export const EXPORTHISTORY_SET_DATASETID = "EXPORTHISTORY_SET_DATASETID";

export const EXPORTHISTORY_SET_ADV_MATCHED_LOOKUP =
  "EXPORTHISTORY_SET_ADV_MATCHED_LOOKUP";
export const EXPORTHISTORY_SET_MATCHED_LOOKUP = "EXPORTHISTORY_SET_MATCHED_LOOKUP";
export const EXPORTHISTORY_TOGGLE_COLUMN_ISMAPPING =
  "EXPORTHISTORY_TOGGLE_COLUMN_ISMAPPING";
export const EXPORTHISTORY_TOGGLE_FILTER_ISMAPPING =
  "EXPORTHISTORY_TOGGLE_FILTER_ISMAPPING";
export const EXPORTHISTORY_CREATE_HOR_GROUPBYDATA =
  "EXPORTHISTORY_CREATE_HOR_GROUPBYDATA";
export const EXPORTHISTORY_CHANGE_HORIZONTAL_GROUPBY =
  "EXPORTHISTORY_CHANGE_HORIZONTAL_GROUPBY";

export const EXPORTHISTORY_SELECTED_FILTER_VALUE =
  "EXPORTHISTORY_SELECTED_FILTER_VALUE";
export const EXPORTHISTORY_ADD_ADDITIONAL_FILTER =
  "EXPORTHISTORY_ADD_ADDITIONAL_FILTER";
export const EXPORTHISTORY_SET_DROPDOWN_CHECKED = "EXPORTHISTORY_SET_DROPDOWN_CHECKED";
export const EXPORTHISTORY_SET_MULTISELECT_CHECKED =
  "EXPORTHISTORY_SET_MULTISELECT_CHECKED";
export const EXPORTHISTORY_SET_ADV_MULTISELECT_CHECKED =
  "EXPORTHISTORY_SET_ADV_MULTISELECT_CHECKED";
export const EXPORTHISTORY_SET_ADV_DROPDOWN_CHECKED =
  "EXPORTHISTORY_SET_ADV_DROPDOWN_CHECKED";

export const EXPORTHISTORY_REMOVE_ALL_FILTER = "EXPORTHISTORY_REMOVE_ALL_FILTER";
export const EXPORTHISTORY_REMOVE_QUICK_FILTER = "EXPORTHISTORY_REMOVE_QUICK_FILTER";
export const EXPORTHISTORY_REMOVE_ADVANCED_FILTER =
  "EXPORTHISTORY_REMOVE_ADVANCED_FILTER";

export const EXPORTHISTORY_QUICK_TEXT_VALUE = "EXPORTHISTORY_QUICK_TEXT_VALUE";
export const EXPORTHISTORY_RESET_QUICK_FILTER_VALUES =
  "EXPORTHISTORY_RESET_QUICK_FILTER_VALUES";

export const EXPORTHISTORY_CREATE_NEW_DATASET = "EXPORTHISTORY_CREATE_NEW_DATASET";
export const EXPORTHISTORY_EDIT_DATASET = "EXPORTHISTORY_EDIT_DATASET";
export const EXPORTHISTORY_GET_NEW_DATASET_INFO_SUCCESS =
  "EXPORTHISTORY_GET_NEW_DATASET_INFO_SUCCESS";
export const EXPORTHISTORY_DELETE_DATASET_DB = "EXPORTHISTORY_DELETE_DATASET_DB";

export const EXPORTHISTORY_SORTED_COLUMN = "EXPORTHISTORY_SORTED_COLUMN";
export const EXPORTHISTORY_SET_COLUMN_SEQ = "EXPORTHISTORY_SET_COLUMN_SEQ";
export const EXPORTHISTORY_SET_NEW_LAYOUT = "EXPORTHISTORY_SET_NEW_LAYOUT";

export const EXPORTHISTORY_SET_DATEPICKER_VALUE = "EXPORTHISTORY_SET_DATEPICKER_VALUE";
export const EXPORTHISTORY_SET_WEEKFILTER_VALUE = "EXPORTHISTORY_SET_WEEKFILTER_VALUE";

export const EXPORTHISTORY_RESET_DATE_FILTERS = "EXPORTHISTORY_RESET_DATE_FILTERS ";
export const EXPORTHISTORY_CHANGE_MASTER_DATA = "EXPORTHISTORY_CHANGE_MASTER_DATA ";

export const EXPORTHISTORY_GET_USERNAME = "EXPORTHISTORY_GET_USERNAME ";
export const EXPORTHISTORY_SET_LOADING = "EXPORTHISTORY_SET_LOADING ";
export const EXPORTHISTORY_SET_TRANSACTIONID = "EXPORTHISTORY_SET_TRANSACTIONID ";
export const EXPORTHISTORY_360_FETCH_LIST_FIELDS_SUCCESS =
  "EXPORTHISTORY_360_FETCH_LIST_FIELDS_SUCCESS ";
export const EXPORTHISTORY_360_TASK_ROW_DATA = "EXPORTHISTORY_360_TASK_ROW_DATA ";
export const EXPORTHISTORY_360_DATASET_SUCCESS = "EXPORTHISTORY_360_DATASET_SUCCESS ";
export const EXPORTHISTORY_360_FETCH_SUB_LIST_FIELDS_SUCCESS =
  "EXPORTHISTORY_360_FETCH_SUB_LIST_FIELDS_SUCCESS ";
export const EXPORTHISTORY_360_SUB_TASK_ROW_DATA =
  "EXPORTHISTORY_360_SUB_TASK_ROW_DATA ";
export const EXPORTHISTORY_360_SUB_DATASET_SUCCESS =
  "EXPORTHISTORY_360_SUB_DATASET_SUCCESS ";

export const EXPORTHISTORY_EDIT_CELL = "EXPORTHISTORY_EDIT_CELL ";
export const EXPORTHISTORY_RESET_EDIT_CELL = "EXPORTHISTORY_RESET_EDIT_CELL ";
