export const FEATURES_FETCH_ENTITY_DATA_SUCCESS =
  "FEATURES_FETCH_ENTITY_DATA_SUCCESS";
export const FEATURES_SELECT_NEW_ENTITY = "FEATURES_SELECT_NEW_ENTITY";

export const FEATURES_FETCH_MASTER_DATA_SUCCESS =
  "FEATURES_FETCH_MASTER_DATA_SUCCESS";
export const FEATURES_FETCH_LIST_FIELDS_SUCCESS =
  "FEATURES_FETCH_LIST_FIELDS_SUCCESS";
export const FEATURES_FETCH_LIST_DATA_SUCCESS =
  "FEATURES_FETCH_LIST_DATA_SUCCESS";
export const FEATURES_FETCH_DATASET_SUCCESS = "FEATURES_FETCH_DATASET_SUCCESS";

export const FEATURES_SET_PAGINATION = "FEATURES_SET_PAGINATION";
export const FEATURES_SET_PAGE_SIZE = "FEATURES_SET_PAGE_SIZE";
export const FEATURES_INCREMENT_COUNT = "FEATURES_INCREMENT_COUNT";
export const FEATURES_SET_DATASETID = "FEATURES_SET_DATASETID";

export const FEATURES_SET_ADV_MATCHED_LOOKUP =
  "FEATURES_SET_ADV_MATCHED_LOOKUP";
export const FEATURES_SET_MATCHED_LOOKUP = "FEATURES_SET_MATCHED_LOOKUP";
export const FEATURES_TOGGLE_COLUMN_ISMAPPING =
  "FEATURES_TOGGLE_COLUMN_ISMAPPING";
export const FEATURES_TOGGLE_FILTER_ISMAPPING =
  "FEATURES_TOGGLE_FILTER_ISMAPPING";
export const FEATURES_CREATE_HOR_GROUPBYDATA =
  "FEATURES_CREATE_HOR_GROUPBYDATA";
export const FEATURES_CHANGE_HORIZONTAL_GROUPBY =
  "FEATURES_CHANGE_HORIZONTAL_GROUPBY";

export const FEATURES_SELECTED_FILTER_VALUE = "FEATURES_SELECTED_FILTER_VALUE";
export const FEATURES_REMOVE_TEXT_FILTER = "FEATURES_REMOVE_TEXT_FILTER";
export const FEATURES_ADD_ADDITIONAL_FILTER = "FEATURES_ADD_ADDITIONAL_FILTER";
export const FEATURES_SET_DROPDOWN_CHECKED = "FEATURES_SET_DROPDOWN_CHECKED";
export const FEATURES_SET_MULTISELECT_CHECKED =
  "FEATURES_SET_MULTISELECT_CHECKED";
export const FEATURES_SET_ADV_MULTISELECT_CHECKED =
  "FEATURES_SET_ADV_MULTISELECT_CHECKED";
export const FEATURES_SET_ADV_DROPDOWN_CHECKED =
  "FEATURES_SET_ADV_DROPDOWN_CHECKED";

export const FEATURES_REMOVE_ALL_FILTER = "FEATURES_REMOVE_ALL_FILTER";
export const FEATURES_REMOVE_QUICK_FILTER = "FEATURES_REMOVE_QUICK_FILTER";
export const FEATURES_REMOVE_ADVANCED_FILTER =
  "FEATURES_REMOVE_ADVANCED_FILTER";

export const FEATURES_QUICK_TEXT_VALUE = "FEATURES_QUICK_TEXT_VALUE";
export const FEATURES_RESET_QUICK_FILTER_VALUES =
  "FEATURES_RESET_QUICK_FILTER_VALUES";

export const FEATURES_CREATE_NEW_DATASET = "FEATURES_CREATE_NEW_DATASET";
export const FEATURES_EDIT_DATASET = "FEATURES_EDIT_DATASET";
export const FEATURES_GET_NEW_DATASET_INFO_SUCCESS =
  "FEATURES_GET_NEW_DATASET_INFO_SUCCESS";
export const FEATURES_DELETE_DATASET_DB = "FEATURES_DELETE_DATASET_DB";

export const FEATURES_SORTED_COLUMN = "FEATURES_SORTED_COLUMN";
export const FEATURES_SET_COLUMN_SEQ = "FEATURES_SET_COLUMN_SEQ";
export const FEATURES_SET_NEW_LAYOUT = "FEATURES_SET_NEW_LAYOUT";
export const FEATURES_SET_DATEPICKER_VALUE = "FEATURES_SET_DATEPICKER_VALUE";
export const FEATURES_SET_WEEKFILTER_VALUE = "FEATURES_SET_WEEKFILTER_VALUE";
export const FEATURES_RESET_DATE_FILTERS = "FEATURES_RESET_DATE_FILTERS";
export const FEATURES_CHANGE_MASTER_DATA = "FEATURES_CHANGE_MASTER_DATA";
export const FEATURES_GET_USERNAME = "FEATURES_GET_USERNAME";
export const FEATURES_SET_LOADING = "FEATURES_SET_LOADING";
export const FEATURES_EDIT_CELL = "FEATURES_EDIT_CELL";
export const FEATURES_RESET_EDIT_CELL = "FEATURES_RESET_EDIT_CELL";
