export const TASK_FETCH_ENTITY_DATA_SUCCESS = "TASK_FETCH_ENTITY_DATA_SUCCESS";
export const TASK_SELECT_NEW_ENTITY = "TASK_SELECT_NEW_ENTITY";

export const TASK_FETCH_MASTER_DATA_SUCCESS = "TASK_FETCH_MASTER_DATA_SUCCESS";
export const TASK_FETCH_LIST_FIELDS_SUCCESS = "TASK_FETCH_LIST_FIELDS_SUCCESS";
export const TASK_FETCH_LIST_DATA_SUCCESS = "TASK_FETCH_LIST_DATA_SUCCESS";
export const TASK_FETCH_DATASET_SUCCESS = "TASK_FETCH_DATASET_SUCCESS";

export const TASK_SET_PAGINATION = "TASK_SET_PAGINATION";
export const TASK_SET_PAGE_SIZE = "TASK_SET_PAGE_SIZE";
export const TASK_INCREMENT_COUNT = "TASK_INCREMENT_COUNT";
export const TASK_SET_DATASETID = "TASK_SET_DATASETID";

export const TASK_SET_ADV_MATCHED_LOOKUP = "TASK_SET_ADV_MATCHED_LOOKUP";
export const TASK_SET_MATCHED_LOOKUP = "TASK_SET_MATCHED_LOOKUP";
export const TASK_TOGGLE_COLUMN_ISMAPPING = "TASK_TOGGLE_COLUMN_ISMAPPING";
export const TASK_TOGGLE_FILTER_ISMAPPING = "TASK_TOGGLE_FILTER_ISMAPPING";
export const TASK_CREATE_HOR_GROUPBYDATA = "TASK_CREATE_HOR_GROUPBYDATA";
export const TASK_CREATE_HOR_GROUPBYDATA_DIRECTION =
  "TASK_CREATE_HOR_GROUPBYDATA_DIRECTION";
export const TASK_CHANGE_HORIZONTAL_GROUPBY = "TASK_CHANGE_HORIZONTAL_GROUPBY";

export const TASK_SELECTED_FILTER_VALUE = "TASK_SELECTED_FILTER_VALUE";
export const TASK_ADD_ADDITIONAL_FILTER = "TASK_ADD_ADDITIONAL_FILTER";
export const TASK_SET_DROPDOWN_CHECKED = "TASK_SET_DROPDOWN_CHECKED";
export const TASK_SET_MULTISELECT_CHECKED = "TASK_SET_MULTISELECT_CHECKED";
export const TASK_SET_ADV_MULTISELECT_CHECKED =
  "TASK_SET_ADV_MULTISELECT_CHECKED";
export const TASK_SET_ADV_DROPDOWN_CHECKED = "TASK_SET_ADV_DROPDOWN_CHECKED";

export const TASK_REMOVE_ALL_FILTER = "TASK_REMOVE_ALL_FILTER";
export const TASK_REMOVE_QUICK_FILTER = "TASK_REMOVE_QUICK_FILTER";
export const TASK_REMOVE_ADVANCED_FILTER = "TASK_REMOVE_ADVANCED_FILTER";

export const TASK_QUICK_TEXT_VALUE = "TASK_QUICK_TEXT_VALUE";
export const TASK_RESET_QUICK_FILTER_VALUES = "TASK_RESET_QUICK_FILTER_VALUES";

export const TASK_CREATE_NEW_DATASET = "TASK_CREATE_NEW_DATASET";
export const TASK_EDIT_DATASET = "TASK_EDIT_DATASET";
export const TASK_GET_NEW_DATASET_INFO_SUCCESS =
  "TASK_GET_NEW_DATASET_INFO_SUCCESS";
export const TASK_DELETE_DATASET_DB = "TASK_DELETE_DATASET_DB";

export const TASK_SORTED_COLUMN = "TASK_SORTED_COLUMN";
export const TASK_SET_COLUMN_SEQ = "TASK_SET_COLUMN_SEQ";
export const TASK_SET_NEW_LAYOUT = "TASK_SET_NEW_LAYOUT";
export const TASK_SET_DATEPICKER_VALUE = "TASK_SET_DATEPICKER_VALUE";
export const TASK_SET_WEEKFILTER_VALUE = "TASK_SET_WEEKFILTER_VALUE";
export const TASK_RESET_DATE_FILTERS = "TASK_RESET_DATE_FILTERS";
export const TASK_CHANGE_MASTER_DATA = "TASK_CHANGE_MASTER_DATA";
export const TASK_GET_USERNAME = "TASK_GET_USERNAME";
export const TASK_GET_USERMAIL = "TASK_GET_USERMAIL";
export const TASK_SET_LOADING = "TASK_SET_LOADING";
export const TASK_EDIT_CELL = "TASK_EDIT_CELL";
export const TASK_SET_CURRENTPAGE = "TASK_SET_CURRENTPAGE";
export const TASK_RESET_EDIT_CELL = "TASK_RESET_EDIT_CELL";
