export const TAG_FETCH_ENTITY_DATA_SUCCESS = "TAG_FETCH_ENTITY_DATA_SUCCESS";
export const TAG_SELECT_NEW_ENTITY = "TAG_SELECT_NEW_ENTITY";

export const TAG_FETCH_MASTER_DATA_SUCCESS = "TAG_FETCH_MASTER_DATA_SUCCESS";
export const TAG_FETCH_LIST_FIELDS_SUCCESS = "TAG_FETCH_LIST_FIELDS_SUCCESS";
export const TAG_FETCH_LIST_DATA_SUCCESS = "TAG_FETCH_LIST_DATA_SUCCESS";
export const TAG_FETCH_DATASET_SUCCESS = "TAG_FETCH_DATASET_SUCCESS";

export const TAG_SET_PAGINATION = "TAG_SET_PAGINATION";
export const TAG_SET_PAGE_SIZE = "TAG_SET_PAGE_SIZE";
export const TAG_INCREMENT_COUNT = "TAG_INCREMENT_COUNT";
export const TAG_SET_DATASETID = "TAG_SET_DATASETID";

export const TAG_SET_ADV_MATCHED_LOOKUP = "TAG_SET_ADV_MATCHED_LOOKUP";
export const TAG_SET_MATCHED_LOOKUP = "TAG_SET_MATCHED_LOOKUP";
export const TAG_TOGGLE_COLUMN_ISMAPPING = "TAG_TOGGLE_COLUMN_ISMAPPING";
export const TAG_TOGGLE_FILTER_ISMAPPING = "TAG_TOGGLE_FILTER_ISMAPPING";
export const TAG_CREATE_HOR_GROUPBYDATA = "TAG_CREATE_HOR_GROUPBYDATA";
export const TAG_CHANGE_HORIZONTAL_GROUPBY = "TAG_CHANGE_HORIZONTAL_GROUPBY";

export const TAG_SELECTED_FILTER_VALUE = "TAG_SELECTED_FILTER_VALUE";
export const TAG_REMOVE_TEXT_FILTER = "TAG_REMOVE_TEXT_FILTER";
export const TAG_ADD_ADDITIONAL_FILTER = "TAG_ADD_ADDITIONAL_FILTER";
export const TAG_SET_DROPDOWN_CHECKED = "TAG_SET_DROPDOWN_CHECKED";
export const TAG_SET_MULTISELECT_CHECKED = "TAG_SET_MULTISELECT_CHECKED";
export const TAG_SET_ADV_MULTISELECT_CHECKED =
  "TAG_SET_ADV_MULTISELECT_CHECKED";
export const TAG_SET_ADV_DROPDOWN_CHECKED = "TAG_SET_ADV_DROPDOWN_CHECKED";

export const TAG_REMOVE_ALL_FILTER = "TAG_REMOVE_ALL_FILTER";
export const TAG_REMOVE_QUICK_FILTER = "TAG_REMOVE_QUICK_FILTER";
export const TAG_REMOVE_ADVANCED_FILTER = "TAG_REMOVE_ADVANCED_FILTER";

export const TAG_QUICK_TEXT_VALUE = "TAG_QUICK_TEXT_VALUE";
export const TAG_RESET_QUICK_FILTER_VALUES = "TAG_RESET_QUICK_FILTER_VALUES";

export const TAG_CREATE_NEW_DATASET = "TAG_CREATE_NEW_DATASET";
export const TAG_EDIT_DATASET = "TAG_EDIT_DATASET";
export const TAG_GET_NEW_DATASET_INFO_SUCCESS =
  "TAG_GET_NEW_DATASET_INFO_SUCCESS";
export const TAG_DELETE_DATASET_DB = "TAG_DELETE_DATASET_DB";

export const TAG_SORTED_COLUMN = "TAG_SORTED_COLUMN";
export const TAG_SET_COLUMN_SEQ = "TAG_SET_COLUMN_SEQ";
export const TAG_SET_NEW_LAYOUT = "TAG_SET_NEW_LAYOUT";
export const TAG_SET_DATEPICKER_VALUE = "TAG_SET_DATEPICKER_VALUE";
export const TAG_SET_WEEKFILTER_VALUE = "TAG_SET_WEEKFILTER_VALUE";
export const TAG_RESET_DATE_FILTERS = "TAG_RESET_DATE_FILTERS";
export const TAG_CHANGE_MASTER_DATA = "TAG_CHANGE_MASTER_DATA";
export const TAG_GET_USERNAME = "TAG_GET_USERNAME";
export const TAG_SET_LOADING = "TAG_SET_LOADING";
export const TAG_EDIT_CELL = "TAG_EDIT_CELL";
export const TAG_RESET_EDIT_CELL = "TAG_RESET_EDIT_CELL";
export const TAG_SET_CURRENTPAGE = "TAG_SET_CURRENTPAGE";
